"""initial_schema

Revision ID: 890d75f54f33
Revises: 
Create Date: 2025-12-29 12:33:11.810919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '890d75f54f33'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_results',
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('cleaned_data_id', sa.String(), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('insights', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('trends', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_analysis_results_analyzed_at', 'analysis_results', ['analyzed_at'], unique=False)
    op.create_index('ix_analysis_results_domain', 'analysis_results', ['domain'], unique=False)
    op.create_table('cars',
    sa.Column('make', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('condition', sa.String(), nullable=False),
    sa.Column('mileage', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('vin', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('transmission', sa.String(), nullable=True),
    sa.Column('fuel_type', sa.String(), nullable=True),
    sa.Column('features', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('seller_type', sa.String(), nullable=False),
    sa.Column('seller_name', sa.String(), nullable=True),
    sa.Column('seller_rating', sa.Float(), nullable=True),
    sa.Column('seller_contact', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('images', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vin')
    )
    op.create_index('ix_cars_condition', 'cars', ['condition'], unique=False)
    op.create_index('ix_cars_make_model', 'cars', ['make', 'model'], unique=False)
    op.create_index('ix_cars_price', 'cars', ['price'], unique=False)
    op.create_index('ix_cars_year', 'cars', ['year'], unique=False)
    op.create_table('cleaned_data',
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('raw_data_id', sa.String(), nullable=False),
    sa.Column('normalized_content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('quality', sa.Float(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cleaned_data_domain', 'cleaned_data', ['domain'], unique=False)
    op.create_index('ix_cleaned_data_quality', 'cleaned_data', ['quality'], unique=False)
    op.create_table('education',
    sa.Column('institution', sa.String(), nullable=False),
    sa.Column('program', sa.String(), nullable=False),
    sa.Column('degree', sa.String(), nullable=False),
    sa.Column('major', sa.String(), nullable=False),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('tuition', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('overall_ranking', sa.Integer(), nullable=True),
    sa.Column('program_ranking', sa.Integer(), nullable=True),
    sa.Column('ranking_source', sa.String(), nullable=True),
    sa.Column('admission_rate', sa.Float(), nullable=True),
    sa.Column('average_gpa', sa.Float(), nullable=True),
    sa.Column('employment_rate', sa.Float(), nullable=True),
    sa.Column('average_salary', sa.Float(), nullable=True),
    sa.Column('application_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_education_degree_major', 'education', ['degree', 'major'], unique=False)
    op.create_index('ix_education_institution', 'education', ['institution'], unique=False)
    op.create_index('ix_education_tuition', 'education', ['tuition'], unique=False)
    op.create_table('flights',
    sa.Column('airline', sa.String(), nullable=False),
    sa.Column('flight_number', sa.String(), nullable=False),
    sa.Column('departure_code', sa.String(), nullable=False),
    sa.Column('departure_name', sa.String(), nullable=False),
    sa.Column('departure_city', sa.String(), nullable=False),
    sa.Column('arrival_code', sa.String(), nullable=False),
    sa.Column('arrival_name', sa.String(), nullable=False),
    sa.Column('arrival_city', sa.String(), nullable=False),
    sa.Column('departure_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('arrival_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('stops', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('cabin_class', sa.String(), nullable=False),
    sa.Column('available_seats', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_flights_departure_time', 'flights', ['departure_time'], unique=False)
    op.create_index('ix_flights_price', 'flights', ['price'], unique=False)
    op.create_index('ix_flights_route', 'flights', ['departure_code', 'arrival_code'], unique=False)
    op.create_table('hotels',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('review_score', sa.Float(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('price_per_night', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('amenities', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('images', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('distance_to_center', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_hotels_location', 'hotels', ['city', 'state'], unique=False)
    op.create_index('ix_hotels_price', 'hotels', ['price_per_night'], unique=False)
    op.create_index('ix_hotels_review_score', 'hotels', ['review_score'], unique=False)
    op.create_table('houses',
    sa.Column('listing_type', sa.String(), nullable=False),
    sa.Column('property_type', sa.String(), nullable=False),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('bedrooms', sa.Integer(), nullable=False),
    sa.Column('bathrooms', sa.Float(), nullable=False),
    sa.Column('square_feet', sa.Integer(), nullable=True),
    sa.Column('lot_size', sa.Integer(), nullable=True),
    sa.Column('year_built', sa.Integer(), nullable=True),
    sa.Column('features', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('school_district_name', sa.String(), nullable=True),
    sa.Column('school_district_rating', sa.Float(), nullable=True),
    sa.Column('nearby_amenities', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('images', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('agent_name', sa.String(), nullable=True),
    sa.Column('agent_contact', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_houses_bedrooms', 'houses', ['bedrooms'], unique=False)
    op.create_index('ix_houses_listing_type', 'houses', ['listing_type'], unique=False)
    op.create_index('ix_houses_location', 'houses', ['city', 'state'], unique=False)
    op.create_index('ix_houses_price', 'houses', ['price'], unique=False)
    op.create_table('insurance_claims',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('insurance_type', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('claim_number', sa.String(), nullable=True),
    sa.Column('incident_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reported_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('claim_type', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('damage_amount', sa.Float(), nullable=True),
    sa.Column('settled_amount', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('documents', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('photos', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_insurance_claims_incident_date', 'insurance_claims', ['incident_date'], unique=False)
    op.create_index('ix_insurance_claims_status', 'insurance_claims', ['status'], unique=False)
    op.create_index('ix_insurance_claims_type', 'insurance_claims', ['insurance_type'], unique=False)
    op.create_index('ix_insurance_claims_user_id', 'insurance_claims', ['user_id'], unique=False)
    op.create_table('insurance_products',
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('premium', sa.Float(), nullable=False),
    sa.Column('deductible', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('payment_frequency', sa.String(), nullable=False),
    sa.Column('coverage_limit', sa.Float(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('customer_satisfaction', sa.Float(), nullable=True),
    sa.Column('features', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('exclusions', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('discount_types', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('coverage_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('eligibility_criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_insurance_products_premium', 'insurance_products', ['premium'], unique=False)
    op.create_index('ix_insurance_products_provider', 'insurance_products', ['provider'], unique=False)
    op.create_index('ix_insurance_products_type', 'insurance_products', ['type'], unique=False)
    op.create_index('ix_insurance_products_valid_until', 'insurance_products', ['valid_until'], unique=False)
    op.create_table('insurance_providers',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('logo', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('customer_satisfaction', sa.Float(), nullable=True),
    sa.Column('supported_types', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('license_states', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('am_best_rating', sa.String(), nullable=True),
    sa.Column('features', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('discount_programs', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('claims_phone', sa.String(), nullable=True),
    sa.Column('customer_service_hours', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_insurance_providers_code', 'insurance_providers', ['code'], unique=False)
    op.create_index('ix_insurance_providers_rating', 'insurance_providers', ['rating'], unique=False)
    op.create_table('insurance_quotes',
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('session_token', sa.String(), nullable=True),
    sa.Column('insurance_type', sa.String(), nullable=False),
    sa.Column('request_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('zip_code', sa.String(), nullable=False),
    sa.Column('quotes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('comparison_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('product_id', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_insurance_quotes_expires_at', 'insurance_quotes', ['expires_at'], unique=False)
    op.create_index('ix_insurance_quotes_session_token', 'insurance_quotes', ['session_token'], unique=False)
    op.create_index('ix_insurance_quotes_status', 'insurance_quotes', ['status'], unique=False)
    op.create_index('ix_insurance_quotes_type', 'insurance_quotes', ['insurance_type'], unique=False)
    op.create_index('ix_insurance_quotes_user_id', 'insurance_quotes', ['user_id'], unique=False)
    op.create_index('ix_insurance_quotes_zip_code', 'insurance_quotes', ['zip_code'], unique=False)
    op.create_table('investments',
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('current_price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('risk_level', sa.String(), nullable=False),
    sa.Column('minimum_investment', sa.Float(), nullable=True),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('dividend_yield', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker')
    )
    op.create_index('ix_investments_price', 'investments', ['current_price'], unique=False)
    op.create_index('ix_investments_risk_level', 'investments', ['risk_level'], unique=False)
    op.create_index('ix_investments_type', 'investments', ['type'], unique=False)
    op.create_table('jobs',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('job_type', sa.String(), nullable=False),
    sa.Column('salary_min', sa.Float(), nullable=True),
    sa.Column('salary_max', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('pay_period', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('requirements', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('benefits', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('hours_per_week', sa.Integer(), nullable=True),
    sa.Column('flexibility', sa.String(), nullable=True),
    sa.Column('shifts', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('posted_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('application_url', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_jobs_location', 'jobs', ['city', 'state'], unique=False)
    op.create_index('ix_jobs_salary', 'jobs', ['salary_min', 'salary_max'], unique=False)
    op.create_index('ix_jobs_type', 'jobs', ['job_type'], unique=False)
    op.create_table('price_history',
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_price_history_domain_item', 'price_history', ['domain', 'item_id'], unique=False)
    op.create_index('ix_price_history_timestamp', 'price_history', ['timestamp'], unique=False)
    op.create_table('raw_data',
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_raw_data_domain', 'raw_data', ['domain'], unique=False)
    op.create_index('ix_raw_data_scraped_at', 'raw_data', ['scraped_at'], unique=False)
    op.create_index('ix_raw_data_status', 'raw_data', ['status'], unique=False)
    op.create_table('recommendations',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('ranking', sa.Integer(), nullable=False),
    sa.Column('pros', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('cons', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('alternative_ids', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recommendations_match_score', 'recommendations', ['match_score'], unique=False)
    op.create_index('ix_recommendations_user_domain', 'recommendations', ['user_id', 'domain'], unique=False)
    op.create_table('search_history',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_search_history_created_at', 'search_history', ['created_at'], unique=False)
    op.create_index('ix_search_history_domain', 'search_history', ['domain'], unique=False)
    op.create_index('ix_search_history_user_id', 'search_history', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('budget', sa.Float(), nullable=True),
    sa.Column('risk_tolerance', sa.String(), nullable=True),
    sa.Column('user_type', sa.String(), nullable=False),
    sa.Column('is_anonymous', sa.Boolean(), nullable=False),
    sa.Column('session_token', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('search_count', sa.Integer(), nullable=False),
    sa.Column('search_limit', sa.Integer(), nullable=False),
    sa.Column('last_search_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('quota_reset_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('subscription_status', sa.String(), nullable=True),
    sa.Column('subscription_tier', sa.String(), nullable=True),
    sa.Column('subscription_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('session_token')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_index('ix_users_session_token', 'users', ['session_token'], unique=False)
    op.create_index('ix_users_user_type', 'users', ['user_type'], unique=False)
    
    # Grant permissions to Supabase roles for all tables
    tables = [
        'analysis_results', 'cars', 'cleaned_data', 'education', 'flights',
        'hotels', 'houses', 'insurance_claims', 'insurance_products',
        'insurance_providers', 'insurance_quotes', 'investments', 'jobs',
        'price_history', 'raw_data', 'recommendations', 'search_history', 'users'
    ]
    for table in tables:
        op.execute(f"GRANT ALL ON {table} TO service_role")
    
    # Grant read access to authenticated users for some tables
    public_tables = ['flights', 'hotels', 'houses', 'cars', 'jobs', 'education', 'investments']
    for table in public_tables:
        op.execute(f"GRANT SELECT ON {table} TO authenticated")
        op.execute(f"GRANT SELECT ON {table} TO anon")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_user_type', table_name='users')
    op.drop_index('ix_users_session_token', table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_search_history_user_id', table_name='search_history')
    op.drop_index('ix_search_history_domain', table_name='search_history')
    op.drop_index('ix_search_history_created_at', table_name='search_history')
    op.drop_table('search_history')
    op.drop_index('ix_recommendations_user_domain', table_name='recommendations')
    op.drop_index('ix_recommendations_match_score', table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index('ix_raw_data_status', table_name='raw_data')
    op.drop_index('ix_raw_data_scraped_at', table_name='raw_data')
    op.drop_index('ix_raw_data_domain', table_name='raw_data')
    op.drop_table('raw_data')
    op.drop_index('ix_price_history_timestamp', table_name='price_history')
    op.drop_index('ix_price_history_domain_item', table_name='price_history')
    op.drop_table('price_history')
    op.drop_index('ix_jobs_type', table_name='jobs')
    op.drop_index('ix_jobs_salary', table_name='jobs')
    op.drop_index('ix_jobs_location', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index('ix_investments_type', table_name='investments')
    op.drop_index('ix_investments_risk_level', table_name='investments')
    op.drop_index('ix_investments_price', table_name='investments')
    op.drop_table('investments')
    op.drop_index('ix_insurance_quotes_zip_code', table_name='insurance_quotes')
    op.drop_index('ix_insurance_quotes_user_id', table_name='insurance_quotes')
    op.drop_index('ix_insurance_quotes_type', table_name='insurance_quotes')
    op.drop_index('ix_insurance_quotes_status', table_name='insurance_quotes')
    op.drop_index('ix_insurance_quotes_session_token', table_name='insurance_quotes')
    op.drop_index('ix_insurance_quotes_expires_at', table_name='insurance_quotes')
    op.drop_table('insurance_quotes')
    op.drop_index('ix_insurance_providers_rating', table_name='insurance_providers')
    op.drop_index('ix_insurance_providers_code', table_name='insurance_providers')
    op.drop_table('insurance_providers')
    op.drop_index('ix_insurance_products_valid_until', table_name='insurance_products')
    op.drop_index('ix_insurance_products_type', table_name='insurance_products')
    op.drop_index('ix_insurance_products_provider', table_name='insurance_products')
    op.drop_index('ix_insurance_products_premium', table_name='insurance_products')
    op.drop_table('insurance_products')
    op.drop_index('ix_insurance_claims_user_id', table_name='insurance_claims')
    op.drop_index('ix_insurance_claims_type', table_name='insurance_claims')
    op.drop_index('ix_insurance_claims_status', table_name='insurance_claims')
    op.drop_index('ix_insurance_claims_incident_date', table_name='insurance_claims')
    op.drop_table('insurance_claims')
    op.drop_index('ix_houses_price', table_name='houses')
    op.drop_index('ix_houses_location', table_name='houses')
    op.drop_index('ix_houses_listing_type', table_name='houses')
    op.drop_index('ix_houses_bedrooms', table_name='houses')
    op.drop_table('houses')
    op.drop_index('ix_hotels_review_score', table_name='hotels')
    op.drop_index('ix_hotels_price', table_name='hotels')
    op.drop_index('ix_hotels_location', table_name='hotels')
    op.drop_table('hotels')
    op.drop_index('ix_flights_route', table_name='flights')
    op.drop_index('ix_flights_price', table_name='flights')
    op.drop_index('ix_flights_departure_time', table_name='flights')
    op.drop_table('flights')
    op.drop_index('ix_education_tuition', table_name='education')
    op.drop_index('ix_education_institution', table_name='education')
    op.drop_index('ix_education_degree_major', table_name='education')
    op.drop_table('education')
    op.drop_index('ix_cleaned_data_quality', table_name='cleaned_data')
    op.drop_index('ix_cleaned_data_domain', table_name='cleaned_data')
    op.drop_table('cleaned_data')
    op.drop_index('ix_cars_year', table_name='cars')
    op.drop_index('ix_cars_price', table_name='cars')
    op.drop_index('ix_cars_make_model', table_name='cars')
    op.drop_index('ix_cars_condition', table_name='cars')
    op.drop_table('cars')
    op.drop_index('ix_analysis_results_domain', table_name='analysis_results')
    op.drop_index('ix_analysis_results_analyzed_at', table_name='analysis_results')
    op.drop_table('analysis_results')
    # ### end Alembic commands ###
