# ai_skills 领域 URL 资源 - 自动生成
from typing import Any

RAW_AI_SKILLS_URLS: list[dict[str, Any]] = [
    {
        "url": "https://github.com/anthropics/skills/tree/main/template",
        "name": "template-skill",
        "description": "Replace with description of the skill and when Claude should use it.",
        "category": "skill",
        "source": "github",
        "repo": "anthropics/skills",
        "platform": "github",
        "tags": ['skill', 'official'],
        "metadata": {'repo': 'anthropics/skills', 'skill_name': 'template', 'has_skill_md': True, 'name': 'template-skill', 'description': 'Replace with description of the skill and when Claude should use it.', 'instructions': '# Insert instructions below', 'keywords': ['skill', 'official']},
        "is_active": True,
    },
    {
        "url": "https://github.com/anthropics/skills/tree/main/skills/algorithmic-art",
        "name": "algorithmic-art",
        "description": "Creating algorithmic art using p5.js with seeded randomness and interactive parameter exploration. Use this when users request creating art using code, generative art, algorithmic art, flow fields, or particle systems. Create original algorithmic art rather than copying existing artists' work to avoid copyright violations.",
        "category": "skill",
        "source": "github",
        "repo": "anthropics/skills",
        "platform": "github",
        "tags": ['skill', 'official'],
        "metadata": {'repo': 'anthropics/skills', 'skill_name': 'algorithmic-art', 'skill_path': 'skills/algorithmic-art', 'has_skill_md': True, 'name': 'algorithmic-art', 'description': "Creating algorithmic art using p5.js with seeded randomness and interactive parameter exploration. Use this when users request creating art using code, generative art, algorithmic art, flow fields, or particle systems. Create original algorithmic art rather than copying existing artists' work to avoid copyright violations.", 'instructions': 'Algorithmic philosophies are computational aesthetic movements that are then expressed through code. Output .md files (philosophy), .html files (interactive viewer), and .js files (generative algorithms).\n\nThis happens in two steps:\n1. Algorithmic Philosophy Creation (.md file)\n2. Express by creating p5.js generative art (.html + .js files)\n\nFirst, undertake this task:\n\n## ALGORITHMIC PHILOSOPHY CREATION\n\nTo begin, create an ALGORITHMIC PHILOSOPHY (not static images or templates) that will be in', 'keywords': ['skill', 'official']},
        "is_active": True,
    },
    {
        "url": "https://github.com/anthropics/skills/tree/main/skills/brand-guidelines",
        "name": "brand-guidelines",
        "description": "Applies Anthropic's official brand colors and typography to any sort of artifact that may benefit from having Anthropic's look-and-feel. Use it when brand colors or style guidelines, visual formatting, or company design standards apply.",
        "category": "skill",
        "source": "github",
        "repo": "anthropics/skills",
        "platform": "github",
        "tags": ['skill', 'official'],
        "metadata": {'repo': 'anthropics/skills', 'skill_name': 'brand-guidelines', 'skill_path': 'skills/brand-guidelines', 'has_skill_md': True, 'name': 'brand-guidelines', 'description': "Applies Anthropic's official brand colors and typography to any sort of artifact that may benefit from having Anthropic's look-and-feel. Use it when brand colors or style guidelines, visual formatting, or company design standards apply.", 'instructions': "# Anthropic Brand Styling\n\n## Overview\n\nTo access Anthropic's official brand identity and style resources, use this skill.\n\n**Keywords**: branding, corporate identity, visual identity, post-processing, styling, brand colors, typography, Anthropic brand, visual formatting, visual design\n\n## Brand Guidelines\n\n### Colors\n\n**Main Colors:**\n\n- Dark: `#141413` - Primary text and dark backgrounds\n- Light: `#faf9f5` - Light backgrounds and text on dark\n- Mid Gray: `#b0aea5` - Secondary elements\n- Light ", 'keywords': ['skill', 'official']},
        "is_active": True,
    },
    {
        "url": "https://github.com/anthropics/skills/tree/main/skills/canvas-design",
        "name": "canvas-design",
        "description": "Create beautiful visual art in .png and .pdf documents using design philosophy. You should use this skill when the user asks to create a poster, piece of art, design, or other static piece. Create original visual designs, never copying existing artists' work to avoid copyright violations.",
        "category": "skill",
        "source": "github",
        "repo": "anthropics/skills",
        "platform": "github",
        "tags": ['skill', 'official'],
        "metadata": {'repo': 'anthropics/skills', 'skill_name': 'canvas-design', 'skill_path': 'skills/canvas-design', 'has_skill_md': True, 'name': 'canvas-design', 'description': "Create beautiful visual art in .png and .pdf documents using design philosophy. You should use this skill when the user asks to create a poster, piece of art, design, or other static piece. Create original visual designs, never copying existing artists' work to avoid copyright violations.", 'instructions': 'These are instructions for creating design philosophies - aesthetic movements that are then EXPRESSED VISUALLY. Output only .md files, .pdf files, and .png files.\n\nComplete this in two steps:\n1. Design Philosophy Creation (.md file)\n2. Express by creating it on a canvas (.pdf file or .png file)\n\nFirst, undertake this task:\n\n## DESIGN PHILOSOPHY CREATION\n\nTo begin, create a VISUAL PHILOSOPHY (not layouts or templates) that will be interpreted through:\n- Form, space, color, composition\n- Images, g', 'keywords': ['skill', 'official']},
        "is_active": True,
    },
    {
        "url": "https://github.com/anthropics/skills/tree/main/skills/doc-coauthoring",
        "name": "doc-coauthoring",
        "description": "Guide users through a structured workflow for co-authoring documentation. Use when user wants to write documentation, proposals, technical specs, decision docs, or similar structured content. This workflow helps users efficiently transfer context, refine content through iteration, and verify the doc works for readers. Trigger when user mentions writing docs, creating proposals, drafting specs, or similar documentation tasks.",
        "category": "skill",
        "source": "github",
        "repo": "anthropics/skills",
        "platform": "github",
        "tags": ['skill', 'official'],
        "metadata": {'repo': 'anthropics/skills', 'skill_name': 'doc-coauthoring', 'skill_path': 'skills/doc-coauthoring', 'has_skill_md': True, 'name': 'doc-coauthoring', 'description': 'Guide users through a structured workflow for co-authoring documentation. Use when user wants to write documentation, proposals, technical specs, decision docs, or similar structured content. This workflow helps users efficiently transfer context, refine content through iteration, and verify the doc works for readers. Trigger when user mentions writing docs, creating proposals, drafting specs, or similar documentation tasks.', 'instructions': '# Doc Co-Authoring Workflow\n\nThis skill provides a structured workflow for guiding users through collaborative document creation. Act as an active guide, walking users through three stages: Context Gathering, Refinement & Structure, and Reader Testing.\n\n## When to Offer This Workflow\n\n**Trigger conditions:**\n- User mentions writing documentation: "write a doc", "draft a proposal", "create a spec", "write up"\n- User mentions specific doc types: "PRD", "design doc", "decision doc", "RFC"\n- User se', 'keywords': ['skill', 'official']},
        "is_active": True,
    },
    {
        "url": "https://github.com/anthropics/skills/tree/main/skills/docx",
        "name": "docx",
        "description": "Comprehensive document creation, editing, and analysis with support for tracked changes, comments, formatting preservation, and text extraction. When Claude needs to work with professional documents (.docx files) for: (1) Creating new documents, (2) Modifying or editing content, (3) Working with tracked changes, (4) Adding comments, or any other document tasks",
        "category": "skill",
        "source": "github",
        "repo": "anthropics/skills",
        "platform": "github",
        "tags": ['skill', 'official'],
        "metadata": {'repo': 'anthropics/skills', 'skill_name': 'docx', 'skill_path': 'skills/docx', 'has_skill_md': True, 'name': 'docx', 'description': 'Comprehensive document creation, editing, and analysis with support for tracked changes, comments, formatting preservation, and text extraction. When Claude needs to work with professional documents (.docx files) for: (1) Creating new documents, (2) Modifying or editing content, (3) Working with tracked changes, (4) Adding comments, or any other document tasks', 'instructions': '# DOCX creation, editing, and analysis\n\n## Overview\n\nA user may ask you to create, edit, or analyze the contents of a .docx file. A .docx file is essentially a ZIP archive containing XML files and other resources that you can read or edit. You have different tools and workflows available for different tasks.\n\n## Workflow Decision Tree\n\n### Reading/Analyzing Content\nUse "Text extraction" or "Raw XML access" sections below\n\n### Creating New Document\nUse "Creating a new Word document" workflow\n\n###', 'keywords': ['skill', 'official']},
        "is_active": True,
    },
    {
        "url": "https://github.com/anthropics/skills/tree/main/skills/frontend-design",
        "name": "frontend-design",
        "description": "Create distinctive, production-grade frontend interfaces with high design quality. Use this skill when the user asks to build web components, pages, artifacts, posters, or applications (examples include websites, landing pages, dashboards, React components, HTML/CSS layouts, or when styling/beautifying any web UI). Generates creative, polished code and UI design that avoids generic AI aesthetics.",
        "category": "skill",
        "source": "github",
        "repo": "anthropics/skills",
        "platform": "github",
        "tags": ['skill', 'official'],
        "metadata": {'repo': 'anthropics/skills', 'skill_name': 'frontend-design', 'skill_path': 'skills/frontend-design', 'has_skill_md': True, 'name': 'frontend-design', 'description': 'Create distinctive, production-grade frontend interfaces with high design quality. Use this skill when the user asks to build web components, pages, artifacts, posters, or applications (examples include websites, landing pages, dashboards, React components, HTML/CSS layouts, or when styling/beautifying any web UI). Generates creative, polished code and UI design that avoids generic AI aesthetics.', 'instructions': 'This skill guides creation of distinctive, production-grade frontend interfaces that avoid generic "AI slop" aesthetics. Implement real working code with exceptional attention to aesthetic details and creative choices.\n\nThe user provides frontend requirements: a component, page, application, or interface to build. They may include context about the purpose, audience, or technical constraints.\n\n## Design Thinking\n\nBefore coding, understand the context and commit to a BOLD aesthetic direction:\n- *', 'keywords': ['skill', 'official']},
        "is_active": True,
    },
    {
        "url": "https://github.com/anthropics/skills/tree/main/skills/internal-comms",
        "name": "internal-comms",
        "description": "A set of resources to help me write all kinds of internal communications, using the formats that my company likes to use. Claude should use this skill whenever asked to write some sort of internal communications (status reports, leadership updates, 3P updates, company newsletters, FAQs, incident reports, project updates, etc.).",
        "category": "skill",
        "source": "github",
        "repo": "anthropics/skills",
        "platform": "github",
        "tags": ['skill', 'official'],
        "metadata": {'repo': 'anthropics/skills', 'skill_name': 'internal-comms', 'skill_path': 'skills/internal-comms', 'has_skill_md': True, 'name': 'internal-comms', 'description': 'A set of resources to help me write all kinds of internal communications, using the formats that my company likes to use. Claude should use this skill whenever asked to write some sort of internal communications (status reports, leadership updates, 3P updates, company newsletters, FAQs, incident reports, project updates, etc.).', 'instructions': '## When to use this skill\nTo write internal communications, use this skill for:\n- 3P updates (Progress, Plans, Problems)\n- Company newsletters\n- FAQ responses\n- Status reports\n- Leadership updates\n- Project updates\n- Incident reports\n\n## How to use this skill\n\nTo write any internal communication:\n\n1. **Identify the communication type** from the request\n2. **Load the appropriate guideline file** from the `examples/` directory:\n    - `examples/3p-updates.md` - For Progress/Plans/Problems team upda', 'keywords': ['skill', 'official']},
        "is_active": True,
    },
    {
        "url": "https://github.com/anthropics/skills/tree/main/skills/mcp-builder",
        "name": "mcp-builder",
        "description": "Guide for creating high-quality MCP (Model Context Protocol) servers that enable LLMs to interact with external services through well-designed tools. Use when building MCP servers to integrate external APIs or services, whether in Python (FastMCP) or Node/TypeScript (MCP SDK).",
        "category": "skill",
        "source": "github",
        "repo": "anthropics/skills",
        "platform": "github",
        "tags": ['skill', 'official'],
        "metadata": {'repo': 'anthropics/skills', 'skill_name': 'mcp-builder', 'skill_path': 'skills/mcp-builder', 'has_skill_md': True, 'name': 'mcp-builder', 'description': 'Guide for creating high-quality MCP (Model Context Protocol) servers that enable LLMs to interact with external services through well-designed tools. Use when building MCP servers to integrate external APIs or services, whether in Python (FastMCP) or Node/TypeScript (MCP SDK).', 'instructions': '# MCP Server Development Guide\n\n## Overview\n\nCreate MCP (Model Context Protocol) servers that enable LLMs to interact with external services through well-designed tools. The quality of an MCP server is measured by how well it enables LLMs to accomplish real-world tasks.\n\n\n### Phase 2: Implementation\n\n#### 2.1 Set Up Project Structure\n\nSee language-specific guides for project setup:\n- [⚡ TypeScript Guide](./reference/node_mcp_server.md) - Project structure, package.json, tsconfig.json\n- [🐍 Python', 'keywords': ['skill', 'official']},
        "is_active": True,
    },
    {
        "url": "https://github.com/anthropics/skills/tree/main/skills/pdf",
        "name": "pdf",
        "description": "Comprehensive PDF manipulation toolkit for extracting text and tables, creating new PDFs, merging/splitting documents, and handling forms. When Claude needs to fill in a PDF form or programmatically process, generate, or analyze PDF documents at scale.",
        "category": "skill",
        "source": "github",
        "repo": "anthropics/skills",
        "platform": "github",
        "tags": ['skill', 'official'],
        "metadata": {'repo': 'anthropics/skills', 'skill_name': 'pdf', 'skill_path': 'skills/pdf', 'has_skill_md': True, 'name': 'pdf', 'description': 'Comprehensive PDF manipulation toolkit for extracting text and tables, creating new PDFs, merging/splitting documents, and handling forms. When Claude needs to fill in a PDF form or programmatically process, generate, or analyze PDF documents at scale.', 'instructions': '# PDF Processing Guide\n\n## Overview\n\nThis guide covers essential PDF processing operations using Python libraries and command-line tools. For advanced features, JavaScript libraries, and detailed examples, see reference.md. If you need to fill out a PDF form, read forms.md and follow its instructions.\n\n## Quick Start\n\n```python\nfrom pypdf import PdfReader, PdfWriter\n\n# Read a PDF\nreader = PdfReader("document.pdf")\nprint(f"Pages: {len(reader.pages)}")\n\n# Extract text\ntext = ""\nfor page in reader.', 'keywords': ['skill', 'official']},
        "is_active": True,
    },
    {
        "url": "https://github.com/anthropics/skills/tree/main/skills/pptx",
        "name": "pptx",
        "description": "Presentation creation, editing, and analysis. When Claude needs to work with presentations (.pptx files) for: (1) Creating new presentations, (2) Modifying or editing content, (3) Working with layouts, (4) Adding comments or speaker notes, or any other presentation tasks",
        "category": "skill",
        "source": "github",
        "repo": "anthropics/skills",
        "platform": "github",
        "tags": ['skill', 'official'],
        "metadata": {'repo': 'anthropics/skills', 'skill_name': 'pptx', 'skill_path': 'skills/pptx', 'has_skill_md': True, 'name': 'pptx', 'description': 'Presentation creation, editing, and analysis. When Claude needs to work with presentations (.pptx files) for: (1) Creating new presentations, (2) Modifying or editing content, (3) Working with layouts, (4) Adding comments or speaker notes, or any other presentation tasks', 'instructions': '# PPTX creation, editing, and analysis\n\n## Overview\n\nA user may ask you to create, edit, or analyze the contents of a .pptx file. A .pptx file is essentially a ZIP archive containing XML files and other resources that you can read or edit. You have different tools and workflows available for different tasks.\n\n## Reading and analyzing content\n\n### Text extraction\nIf you just need to read the text contents of a presentation, you should convert the document to markdown:\n\n```bash\n# Convert document ', 'keywords': ['skill', 'official']},
        "is_active": True,
    },
    {
        "url": "https://github.com/anthropics/skills/tree/main/skills/skill-creator",
        "name": "skill-creator",
        "description": "Guide for creating effective skills. This skill should be used when users want to create a new skill (or update an existing skill) that extends Claude's capabilities with specialized knowledge, workflows, or tool integrations.",
        "category": "skill",
        "source": "github",
        "repo": "anthropics/skills",
        "platform": "github",
        "tags": ['skill', 'official'],
        "metadata": {'repo': 'anthropics/skills', 'skill_name': 'skill-creator', 'skill_path': 'skills/skill-creator', 'has_skill_md': True, 'name': 'skill-creator', 'description': "Guide for creating effective skills. This skill should be used when users want to create a new skill (or update an existing skill) that extends Claude's capabilities with specialized knowledge, workflows, or tool integrations.", 'instructions': '# Skill Creator\n\nThis skill provides guidance for creating effective skills.\n\n## About Skills\n\nSkills are modular, self-contained packages that extend Claude\'s capabilities by providing\nspecialized knowledge, workflows, and tools. Think of them as "onboarding guides" for specific\ndomains or tasks—they transform Claude from a general-purpose agent into a specialized agent\nequipped with procedural knowledge that no model can fully possess.\n\n### What Skills Provide\n\n1. Specialized workflows - Multi', 'keywords': ['skill', 'official']},
        "is_active": True,
    },
    {
        "url": "https://github.com/anthropics/skills/tree/main/skills/slack-gif-creator",
        "name": "slack-gif-creator",
        "description": "Knowledge and utilities for creating animated GIFs optimized for Slack. Provides constraints, validation tools, and animation concepts. Use when users request animated GIFs for Slack like \"make me a GIF of X doing Y for Slack.",
        "category": "skill",
        "source": "github",
        "repo": "anthropics/skills",
        "platform": "github",
        "tags": ['skill', 'official'],
        "metadata": {'repo': 'anthropics/skills', 'skill_name': 'slack-gif-creator', 'skill_path': 'skills/slack-gif-creator', 'has_skill_md': True, 'name': 'slack-gif-creator', 'description': 'Knowledge and utilities for creating animated GIFs optimized for Slack. Provides constraints, validation tools, and animation concepts. Use when users request animated GIFs for Slack like "make me a GIF of X doing Y for Slack.', 'instructions': '# Slack GIF Creator\n\nA toolkit providing utilities and knowledge for creating animated GIFs optimized for Slack.\n\n## Slack Requirements\n\n**Dimensions:**\n- Emoji GIFs: 128x128 (recommended)\n- Message GIFs: 480x480\n\n**Parameters:**\n- FPS: 10-30 (lower is smaller file size)\n- Colors: 48-128 (fewer = smaller file size)\n- Duration: Keep under 3 seconds for emoji GIFs\n\n## Core Workflow\n\n```python\nfrom core.gif_builder import GIFBuilder\nfrom PIL import Image, ImageDraw\n\n# 1. Create builder\nbuilder = GI', 'keywords': ['skill', 'official']},
        "is_active": True,
    },
    {
        "url": "https://github.com/anthropics/skills/tree/main/skills/theme-factory",
        "name": "theme-factory",
        "description": "Toolkit for styling artifacts with a theme. These artifacts can be slides, docs, reportings, HTML landing pages, etc. There are 10 pre-set themes with colors/fonts that you can apply to any artifact that has been creating, or can generate a new theme on-the-fly.",
        "category": "skill",
        "source": "github",
        "repo": "anthropics/skills",
        "platform": "github",
        "tags": ['skill', 'official'],
        "metadata": {'repo': 'anthropics/skills', 'skill_name': 'theme-factory', 'skill_path': 'skills/theme-factory', 'has_skill_md': True, 'name': 'theme-factory', 'description': 'Toolkit for styling artifacts with a theme. These artifacts can be slides, docs, reportings, HTML landing pages, etc. There are 10 pre-set themes with colors/fonts that you can apply to any artifact that has been creating, or can generate a new theme on-the-fly.', 'instructions': '# Theme Factory Skill\n\nThis skill provides a curated collection of professional font and color themes themes, each with carefully selected color palettes and font pairings. Once a theme is chosen, it can be applied to any artifact.\n\n## Purpose\n\nTo apply consistent, professional styling to presentation slide decks, use this skill. Each theme includes:\n- A cohesive color palette with hex codes\n- Complementary font pairings for headers and body text\n- A distinct visual identity suitable for differe', 'keywords': ['skill', 'official']},
        "is_active": True,
    },
    {
        "url": "https://github.com/anthropics/skills/tree/main/skills/web-artifacts-builder",
        "name": "web-artifacts-builder",
        "description": "Suite of tools for creating elaborate, multi-component claude.ai HTML artifacts using modern frontend web technologies (React, Tailwind CSS, shadcn/ui). Use for complex artifacts requiring state management, routing, or shadcn/ui components - not for simple single-file HTML/JSX artifacts.",
        "category": "skill",
        "source": "github",
        "repo": "anthropics/skills",
        "platform": "github",
        "tags": ['skill', 'official'],
        "metadata": {'repo': 'anthropics/skills', 'skill_name': 'web-artifacts-builder', 'skill_path': 'skills/web-artifacts-builder', 'has_skill_md': True, 'name': 'web-artifacts-builder', 'description': 'Suite of tools for creating elaborate, multi-component claude.ai HTML artifacts using modern frontend web technologies (React, Tailwind CSS, shadcn/ui). Use for complex artifacts requiring state management, routing, or shadcn/ui components - not for simple single-file HTML/JSX artifacts.', 'instructions': '# Web Artifacts Builder\n\nTo build powerful frontend claude.ai artifacts, follow these steps:\n1. Initialize the frontend repo using `scripts/init-artifact.sh`\n2. Develop your artifact by editing the generated code\n3. Bundle all code into a single HTML file using `scripts/bundle-artifact.sh`\n4. Display artifact to user\n5. (Optional) Test the artifact\n\n**Stack**: React 18 + TypeScript + Vite + Parcel (bundling) + Tailwind CSS + shadcn/ui\n\n## Design & Style Guidelines\n\nVERY IMPORTANT: To avoid what ', 'keywords': ['skill', 'official']},
        "is_active": True,
    },
    {
        "url": "https://github.com/anthropics/skills/tree/main/skills/webapp-testing",
        "name": "webapp-testing",
        "description": "Toolkit for interacting with and testing local web applications using Playwright. Supports verifying frontend functionality, debugging UI behavior, capturing browser screenshots, and viewing browser logs.",
        "category": "skill",
        "source": "github",
        "repo": "anthropics/skills",
        "platform": "github",
        "tags": ['skill', 'official'],
        "metadata": {'repo': 'anthropics/skills', 'skill_name': 'webapp-testing', 'skill_path': 'skills/webapp-testing', 'has_skill_md': True, 'name': 'webapp-testing', 'description': 'Toolkit for interacting with and testing local web applications using Playwright. Supports verifying frontend functionality, debugging UI behavior, capturing browser screenshots, and viewing browser logs.', 'instructions': '# Web Application Testing\n\nTo test local web applications, write native Python Playwright scripts.\n\n**Helper Scripts Available**:\n- `scripts/with_server.py` - Manages server lifecycle (supports multiple servers)\n\n**Always run scripts with `--help` first** to see usage. DO NOT read the source until you try running the script first and find that a customized solution is abslutely necessary. These scripts can be very large and thus pollute your context window. They exist to be called directly as bl', 'keywords': ['skill', 'official']},
        "is_active": True,
    },
    {
        "url": "https://github.com/anthropics/skills/tree/main/skills/xlsx",
        "name": "xlsx",
        "description": "Comprehensive spreadsheet creation, editing, and analysis with support for formulas, formatting, data analysis, and visualization. When Claude needs to work with spreadsheets (.xlsx, .xlsm, .csv, .tsv, etc) for: (1) Creating new spreadsheets with formulas and formatting, (2) Reading or analyzing data, (3) Modify existing spreadsheets while preserving formulas, (4) Data analysis and visualization in spreadsheets, or (5) Recalculating formulas",
        "category": "skill",
        "source": "github",
        "repo": "anthropics/skills",
        "platform": "github",
        "tags": ['skill', 'official'],
        "metadata": {'repo': 'anthropics/skills', 'skill_name': 'xlsx', 'skill_path': 'skills/xlsx', 'has_skill_md': True, 'name': 'xlsx', 'description': 'Comprehensive spreadsheet creation, editing, and analysis with support for formulas, formatting, data analysis, and visualization. When Claude needs to work with spreadsheets (.xlsx, .xlsm, .csv, .tsv, etc) for: (1) Creating new spreadsheets with formulas and formatting, (2) Reading or analyzing data, (3) Modify existing spreadsheets while preserving formulas, (4) Data analysis and visualization in spreadsheets, or (5) Recalculating formulas', 'instructions': '# Requirements for Outputs\n\n## All Excel files\n\n### Zero Formula Errors\n- Every Excel model MUST be delivered with ZERO formula errors (#REF!, #DIV/0!, #VALUE!, #N/A, #NAME?)\n\n### Preserve Existing Templates (when updating templates)\n- Study and EXACTLY match existing format, style, and conventions when modifying files\n- Never impose standardized formatting on files with established patterns\n- Existing template conventions ALWAYS override these guidelines\n\n## Financial models\n\n### Color Coding S', 'keywords': ['skill', 'official']},
        "is_active": True,
    },
    {
        "url": "https://github.com/anthropics/skills/tree/main/spec",
        "name": "agent-skills-spec",
        "description": "Agent Skills 规范文档，定义了 skills 的标准格式和最佳实践",
        "category": "documentation",
        "source": "github",
        "repo": "anthropics/skills",
        "platform": "github",
        "tags": ['spec', 'documentation', 'official'],
        "metadata": {'repo': 'anthropics/skills', 'resource_type': 'specification', 'spec_url': 'https://agentskills.io/specification'},
        "is_active": True,
    },
]
