# ai_prompts 领域 URL 资源 - 自动生成
from typing import Any

RAW_AI_PROMPTS_URLS: list[dict[str, Any]] = [
    {
        "url": "https://github.com/anthropics/prompt-eng-interactive-tutorial",
        "name": "Anthropic's Prompt Engineering Tutorial (2024)",
        "description": "",
        "category": "tutorial",
        "source": "hackernews",
        "repo": "anthropics/prompt-eng-interactive-tutorial",
        "platform": "github",
        "tags": ['prompt'],
        "metadata": {'points': 392, 'created_at': '2025-10-11T18:06:40Z', 'quality_score': 87.5, 'quality_details': {'source': 100.0, 'relevance': 75, 'freshness': 75.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://pub.towardsai.net/i-reverse-engineered-200-ai-startups-73-are-lying-a8610acab0d3",
        "name": "73% of AI startups are just prompt engineering",
        "description": "",
        "category": "other",
        "source": "hackernews",
        "repo": "",
        "platform": "web",
        "tags": ['prompt', 'ai'],
        "metadata": {'points': 246, 'created_at': '2025-11-23T16:17:57Z', 'quality_score': 81.5, 'quality_details': {'source': 70.0, 'relevance': 75, 'freshness': 90.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://github.com/anthropics/courses/tree/master/prompt_engineering_interactive_tutorial",
        "name": "Anthropic's Prompt Engineering Interactive Tutorial",
        "description": "",
        "category": "tutorial",
        "source": "hackernews",
        "repo": "anthropics/courses",
        "platform": "github",
        "tags": ['prompt'],
        "metadata": {'points': 284, 'created_at': '2024-08-29T22:21:55Z', 'quality_score': 80.5, 'quality_details': {'source': 100.0, 'relevance': 75, 'freshness': 40.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://github.com/dair-ai/Prompt-Engineering-Guide",
        "name": "Prompt Engineering Guide: Guides, papers, and resources for prompt engineering",
        "description": "",
        "category": "tutorial",
        "source": "hackernews",
        "repo": "dair-ai/Prompt-Engineering-Guide",
        "platform": "github",
        "tags": ['prompt'],
        "metadata": {'points': 544, 'created_at': '2023-02-21T17:01:25Z', 'quality_score': 76.5, 'quality_details': {'source': 100.0, 'relevance': 75, 'freshness': 20.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://github.com/brexhq/prompt-engineering",
        "name": "Brex’s Prompt Engineering Guide",
        "description": "",
        "category": "tutorial",
        "source": "hackernews",
        "repo": "brexhq/prompt-engineering",
        "platform": "github",
        "tags": ['prompt'],
        "metadata": {'points': 540, 'created_at': '2023-05-15T00:12:10Z', 'quality_score': 76.5, 'quality_details': {'source': 100.0, 'relevance': 75, 'freshness': 20.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://github.com/microsoft/prompt-engine",
        "name": "Prompt Engine – Microsoft's prompt engineering library",
        "description": "",
        "category": "library",
        "source": "hackernews",
        "repo": "microsoft/prompt-engine",
        "platform": "github",
        "tags": ['prompt'],
        "metadata": {'points': 309, 'created_at': '2023-02-15T21:46:36Z', 'quality_score': 76.5, 'quality_details': {'source': 100.0, 'relevance': 75, 'freshness': 20.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://simonwillison.net/2023/Oct/26/add-a-walrus/",
        "name": "Now add a walrus: Prompt engineering in DALL-E 3",
        "description": "",
        "category": "other",
        "source": "hackernews",
        "repo": "",
        "platform": "web",
        "tags": ['prompt'],
        "metadata": {'points': 288, 'created_at': '2023-10-26T21:19:22Z', 'quality_score': 76.5, 'quality_details': {'source': 100.0, 'relevance': 75, 'freshness': 20.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://platform.openai.com/docs/guides/prompt-engineering",
        "name": "Prompt engineering",
        "description": "",
        "category": "other",
        "source": "hackernews",
        "repo": "",
        "platform": "web",
        "tags": ['prompt'],
        "metadata": {'points': 281, 'created_at': '2023-12-15T18:30:30Z', 'quality_score': 76.5, 'quality_details': {'source': 100.0, 'relevance': 75, 'freshness': 20.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://addyo.substack.com/p/the-prompt-engineering-playbook-for",
        "name": "Prompt engineering playbook for programmers",
        "description": "",
        "category": "other",
        "source": "hackernews",
        "repo": "",
        "platform": "web",
        "tags": ['prompt'],
        "metadata": {'points': 464, 'created_at': '2025-06-04T15:58:57Z', 'quality_score': 75.5, 'quality_details': {'source': 70.0, 'relevance': 75, 'freshness': 60.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://github.com/sindresorhus/awesome",
        "name": "awesome",
        "description": "😎 Awesome lists about all kinds of interesting topics",
        "category": "other",
        "source": "github",
        "repo": "sindresorhus/awesome",
        "platform": "github",
        "tags": ['awesome', 'awesome-list', 'lists', 'resources', 'unicorns'],
        "metadata": {'stars': 429714, 'updated_at': '2026-01-15T19:50:54Z', 'quality_score': 70.0, 'quality_details': {'source': 100.0, 'relevance': 0.0, 'freshness': 100.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://github.com/awesome-selfhosted/awesome-selfhosted",
        "name": "awesome-selfhosted",
        "description": "A list of Free Software network services and web applications which can be hosted on your own servers",
        "category": "other",
        "source": "github",
        "repo": "awesome-selfhosted/awesome-selfhosted",
        "platform": "github",
        "tags": ['awesome', 'awesome-list', 'cloud', 'free-software', 'hosting', 'privacy', 'self-hosted', 'selfhosted'],
        "metadata": {'stars': 268316, 'updated_at': '2026-01-15T19:55:05Z', 'quality_score': 70.0, 'quality_details': {'source': 100.0, 'relevance': 0.0, 'freshness': 100.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://github.com/ollama/ollama",
        "name": "ollama",
        "description": "Get up and running with OpenAI gpt-oss, DeepSeek-R1, Gemma 3 and other models.",
        "category": "other",
        "source": "github",
        "repo": "ollama/ollama",
        "platform": "github",
        "tags": ['deepseek', 'gemma', 'gemma3', 'gemma3n', 'go', 'golang', 'gpt-oss', 'llama', 'llama2', 'llama3', 'llava', 'llm', 'llms', 'mistral', 'ollama', 'phi4', 'qwen'],
        "metadata": {'stars': 159515, 'updated_at': '2026-01-15T19:31:02Z', 'quality_score': 70.0, 'quality_details': {'source': 100.0, 'relevance': 0.0, 'freshness': 100.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://github.com/f/awesome-chatgpt-prompts",
        "name": "awesome-chatgpt-prompts",
        "description": "Share, discover, and collect prompts from the community. Free and open source — self-host for your organization with complete privacy.",
        "category": "library",
        "source": "github",
        "repo": "f/awesome-chatgpt-prompts",
        "platform": "github",
        "tags": ['bots', 'chatbot', 'chatgpt', 'chatgpt-api', 'language'],
        "metadata": {'stars': 142377, 'updated_at': '2026-01-15T19:44:14Z', 'quality_score': 70.0, 'quality_details': {'source': 100.0, 'relevance': 0.0, 'freshness': 100.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://github.com/ripienaar/free-for-dev",
        "name": "free-for-dev",
        "description": "A list of SaaS, PaaS and IaaS offerings that have free tiers of interest to devops and infradev",
        "category": "other",
        "source": "github",
        "repo": "ripienaar/free-for-dev",
        "platform": "github",
        "tags": ['awesome-list', 'free-for-developers'],
        "metadata": {'stars': 117306, 'updated_at': '2026-01-15T19:03:00Z', 'quality_score': 70.0, 'quality_details': {'source': 100.0, 'relevance': 0.0, 'freshness': 100.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://github.com/x1xhlol/system-prompts-and-models-of-ai-tools",
        "name": "system-prompts-and-models-of-ai-tools",
        "description": "FULL Augment Code, Claude Code, Cluely, CodeBuddy, Comet, Cursor, Devin AI, Junie, Kiro, Leap.new, Lovable, Manus, NotionAI, Orchids.app, Perplexity, Poke, Qoder, Replit, Same.dev, Trae, Traycer AI, VSCode Agent, Warp.dev, Windsurf, Xcode, Z.ai Code, Dia & v0. (And other Open Sourced) System Prompts, Internal Tools & AI Models",
        "category": "library",
        "source": "github",
        "repo": "x1xhlol/system-prompts-and-models-of-ai-tools",
        "platform": "github",
        "tags": ['ai', 'bolt', 'cluely', 'copilot', 'cursor', 'cursorai', 'devin', 'github-copilot', 'lovable', 'open-source', 'perplexity', 'replit', 'system-prompts', 'trae', 'trae-ai', 'trae-ide', 'v0', 'vscode', 'windsurf', 'windsurf-ai'],
        "metadata": {'stars': 108439, 'updated_at': '2026-01-15T19:52:33Z', 'quality_score': 70.0, 'quality_details': {'source': 100.0, 'relevance': 0.0, 'freshness': 100.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://github.com/deepseek-ai/DeepSeek-V3",
        "name": "DeepSeek-V3",
        "description": "",
        "category": "other",
        "source": "github",
        "repo": "deepseek-ai/DeepSeek-V3",
        "platform": "github",
        "tags": [],
        "metadata": {'stars': 101109, 'updated_at': '2026-01-15T19:26:06Z', 'quality_score': 70.0, 'quality_details': {'source': 100.0, 'relevance': 0.0, 'freshness': 100.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://github.com/deepseek-ai/DeepSeek-R1",
        "name": "DeepSeek-R1",
        "description": "",
        "category": "other",
        "source": "github",
        "repo": "deepseek-ai/DeepSeek-R1",
        "platform": "github",
        "tags": [],
        "metadata": {'stars': 91712, 'updated_at': '2026-01-15T17:04:53Z', 'quality_score': 70.0, 'quality_details': {'source': 100.0, 'relevance': 0.0, 'freshness': 100.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://github.com/ChatGPTNextWeb/NextChat",
        "name": "NextChat",
        "description": "✨ Light and Fast AI Assistant. Support: Web | iOS | MacOS | Android |  Linux | Windows",
        "category": "other",
        "source": "github",
        "repo": "ChatGPTNextWeb/NextChat",
        "platform": "github",
        "tags": ['calclaude', 'chatgpt', 'claude', 'cross-platform', 'desktop', 'fe', 'gemini', 'gemini-pro', 'gemini-server', 'gemini-ultra', 'gpt-4o', 'groq', 'nextjs', 'ollama', 'react', 'tauri', 'tauri-app', 'vercel', 'webui'],
        "metadata": {'stars': 87058, 'updated_at': '2026-01-15T18:19:02Z', 'quality_score': 70.0, 'quality_details': {'source': 100.0, 'relevance': 0.0, 'freshness': 100.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://github.com/microsoft/markitdown",
        "name": "markitdown",
        "description": "Python tool for converting files and office documents to Markdown.",
        "category": "tool",
        "source": "github",
        "repo": "microsoft/markitdown",
        "platform": "github",
        "tags": ['autogen', 'autogen-extension', 'langchain', 'markdown', 'microsoft-office', 'openai', 'pdf'],
        "metadata": {'stars': 85269, 'updated_at': '2026-01-15T16:57:32Z', 'quality_score': 70.0, 'quality_details': {'source': 100.0, 'relevance': 0.0, 'freshness': 100.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://github.com/kamranahmedse/developer-roadmap",
        "name": "developer-roadmap",
        "description": "Interactive roadmaps, guides and other educational content to help developers grow in their careers.",
        "category": "tutorial",
        "source": "github",
        "repo": "kamranahmedse/developer-roadmap",
        "platform": "github",
        "tags": ['angular-roadmap', 'backend-roadmap', 'blockchain-roadmap', 'computer-science', 'dba-roadmap', 'developer-roadmap', 'devops-roadmap', 'frontend-roadmap', 'go-roadmap', 'java-roadmap', 'javascript-roadmap', 'nodejs-roadmap', 'python-roadmap', 'qa-roadmap', 'react-roadmap', 'roadmap', 'software-architect-roadmap', 'vue-roadmap'],
        "metadata": {'stars': 347287, 'updated_at': '2026-01-15T19:49:08Z', 'quality_score': 70.0, 'quality_details': {'source': 100.0, 'relevance': 0.0, 'freshness': 100.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://github.com/vinta/awesome-python",
        "name": "awesome-python",
        "description": "An opinionated list of awesome Python frameworks, libraries, software and resources.",
        "category": "library",
        "source": "github",
        "repo": "vinta/awesome-python",
        "platform": "github",
        "tags": ['awesome', 'collections', 'python', 'python-framework', 'python-library', 'python-resources'],
        "metadata": {'stars': 278344, 'updated_at': '2026-01-15T19:54:00Z', 'quality_score': 70.0, 'quality_details': {'source': 100.0, 'relevance': 0.0, 'freshness': 100.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://github.com/trimstray/the-book-of-secret-knowledge",
        "name": "the-book-of-secret-knowledge",
        "description": "A collection of inspiring lists, manuals, cheatsheets, blogs, hacks, one-liners, cli/web tools and more.",
        "category": "library",
        "source": "github",
        "repo": "trimstray/the-book-of-secret-knowledge",
        "platform": "github",
        "tags": ['awesome', 'awesome-list', 'bsd', 'cheatsheets', 'devops', 'guidelines', 'hacking', 'hacks', 'howtos', 'linux', 'lists', 'manuals', 'one-liners', 'pentesters', 'resources', 'search-engines', 'security', 'security-researchers', 'sysops'],
        "metadata": {'stars': 202421, 'updated_at': '2026-01-15T19:37:27Z', 'quality_score': 70.0, 'quality_details': {'source': 100.0, 'relevance': 0.0, 'freshness': 100.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://github.com/avelino/awesome-go",
        "name": "awesome-go",
        "description": "A curated list of awesome Go frameworks, libraries and software",
        "category": "library",
        "source": "github",
        "repo": "avelino/awesome-go",
        "platform": "github",
        "tags": ['awesome', 'awesome-list', 'go', 'golang', 'golang-library', 'hacktoberfest'],
        "metadata": {'stars': 162605, 'updated_at': '2026-01-15T19:33:45Z', 'quality_score': 70.0, 'quality_details': {'source': 100.0, 'relevance': 0.0, 'freshness': 100.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://github.com/microsoft/generative-ai-for-beginners",
        "name": "generative-ai-for-beginners",
        "description": "21 Lessons, Get Started Building with Generative AI ",
        "category": "other",
        "source": "github",
        "repo": "microsoft/generative-ai-for-beginners",
        "platform": "github",
        "tags": ['ai', 'azure', 'chatgpt', 'dall-e', 'generative-ai', 'generativeai', 'gpt', 'language-model', 'llms', 'microsoft-for-beginners', 'openai', 'prompt-engineering', 'semantic-search', 'transformers'],
        "metadata": {'stars': 105199, 'updated_at': '2026-01-15T18:30:50Z', 'quality_score': 70.0, 'quality_details': {'source': 100.0, 'relevance': 0.0, 'freshness': 100.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://github.com/microsoft/terminal",
        "name": "terminal",
        "description": "The new Windows Terminal and the original Windows console host, all in the same place!",
        "category": "other",
        "source": "github",
        "repo": "microsoft/terminal",
        "platform": "github",
        "tags": ['cmd', 'command-line', 'console', 'contributions-welcome', 'good-first-issue', 'hacktoberfest', 'terminal', 'windows', 'windows-console', 'windows-terminal', 'wsl'],
        "metadata": {'stars': 101380, 'updated_at': '2026-01-15T19:20:27Z', 'quality_score': 70.0, 'quality_details': {'source': 100.0, 'relevance': 0.0, 'freshness': 100.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://github.com/punkpeye/awesome-mcp-servers",
        "name": "awesome-mcp-servers",
        "description": "A collection of MCP servers.",
        "category": "library",
        "source": "github",
        "repo": "punkpeye/awesome-mcp-servers",
        "platform": "github",
        "tags": ['ai', 'mcp'],
        "metadata": {'stars': 78946, 'updated_at': '2026-01-15T19:31:07Z', 'quality_score': 70.0, 'quality_details': {'source': 100.0, 'relevance': 0.0, 'freshness': 100.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://github.com/fighting41love/funNLP",
        "name": "funNLP",
        "description": "中英文敏感词、语言检测、中外手机/电话归属地/运营商查询、名字推断性别、手机号抽取、身份证抽取、邮箱抽取、中日文人名库、中文缩写库、拆字词典、词汇情感值、停用词、反动词表、暴恐词表、繁简体转换、英文模拟中文发音、汪峰歌词生成器、职业名称词库、同义词库、反义词库、否定词库、汽车品牌词库、汽车零件词库、连续英文切割、各种中文词向量、公司名字大全、古诗词库、IT词库、财经词库、成语词库、地名词库、历史名人词库、诗词词库、医学词库、饮食词库、法律词库、汽车词库、动物词库、中文聊天语料、中文谣言数据、百度中文问答数据集、句子相似度匹配算法集合、bert资源、文本生成&摘要相关工具、cocoNLP信息抽取工具、国内电话号码正则匹配、清华大学XLORE:中英文跨语言百科知识图谱、清华大学人工智能技术系列报告、自然语言生成、NLU太难了系列、自动对联数据及机器人、用户名黑名单列表、罪名法务名词及分类模型、微信公众号语料、cs224n深度学习自然语言处理课程、中文手写汉字识别、中文自然语言处理 语料/数据集、变量命名神器、分词语料库+代码、任务型对话英文数据集、ASR 语音数据集 + 基于深度学习的中文语音识别系统、笑声检测器、Microsoft多语言数字/单位/如日期时间识别包、中华新华字典数据库及api(包括常用歇后语、成语、词语和汉字)、文档图谱自动生成、SpaCy 中文模型、Common Voice语音识别数据集新版、神经网络关系抽取、基于bert的命名实体识别、关键词(Keyphrase)抽取包pke、基于医疗领域知识图谱的问答系统、基于依存句法与语义角色标注的事件三元组抽取、依存句法分析4万句高质量标注数据、cnocr：用来做中文OCR的Python3包、中文人物关系知识图谱项目、中文nlp竞赛项目及代码汇总、中文字符数据、speech-aligner: 从“人声语音”及其“语言文本”产生音素级别时间对齐标注的工具、AmpliGraph: 知识图谱表示学习(Python)库：知识图谱概念链接预测、Scattertext 文本可视化(python)、语言/知识表示工具：BERT & ERNIE、中文对比英文自然语言处理NLP的区别综述、Synonyms中文近义词工具包、HarvestText领域自适应文本挖掘工具（新词发现-情感分析-实体链接等）、word2word：(Python)方便易用的多语言词-词对集：62种语言/3,564个多语言对、语音识别语料生成工具：从具有音频/字幕的在线视频创建自动语音识别(ASR)语料库、构建医疗实体识别的模型（包含词典和语料标注）、单文档非监督的关键词抽取、Kashgari中使用gpt-2语言模型、开源的金融投资数据提取工具、文本自动摘要库TextTeaser: 仅支持英文、人民日报语料处理工具集、一些关于自然语言的基本模型、基于14W歌曲知识库的问答尝试--功能包括歌词接龙and已知歌词找歌曲以及歌曲歌手歌词三角关系的问答、基于Siamese bilstm模型的相似句子判定模型并提供训练数据集和测试数据集、用Transformer编解码模型实现的根据Hacker News文章标题自动生成评论、用BERT进行序列标记和文本分类的模板代码、LitBank：NLP数据集——支持自然语言处理和计算人文学科任务的100部带标记英文小说语料、百度开源的基准信息抽取系统、虚假新闻数据集、Facebook: LAMA语言模型分析，提供Transformer-XL/BERT/ELMo/GPT预训练语言模型的统一访问接口、CommonsenseQA：面向常识的英文QA挑战、中文知识图谱资料、数据及工具、各大公司内部里大牛分享的技术文档 PDF 或者 PPT、自然语言生成SQL语句（英文）、中文NLP数据增强（EDA）工具、英文NLP数据增强工具 、基于医药知识图谱的智能问答系统、京东商品知识图谱、基于mongodb存储的军事领域知识图谱问答项目、基于远监督的中文关系抽取、语音情感分析、中文ULMFiT-情感分析-文本分类-语料及模型、一个拍照做题程序、世界各国大规模人名库、一个利用有趣中文语料库 qingyun 训练出来的中文聊天机器人、中文聊天机器人seqGAN、省市区镇行政区划数据带拼音标注、教育行业新闻语料库包含自动文摘功能、开放了对话机器人-知识图谱-语义理解-自然语言处理工具及数据、中文知识图谱：基于百度百科中文页面-抽取三元组信息-构建中文知识图谱、masr: 中文语音识别-提供预训练模型-高识别率、Python音频数据增广库、中文全词覆盖BERT及两份阅读理解数据、ConvLab：开源多域端到端对话系统平台、中文自然语言处理数据集、基于最新版本rasa搭建的对话系统、基于TensorFlow和BERT的管道式实体及关系抽取、一个小型的证券知识图谱/知识库、复盘所有NLP比赛的TOP方案、OpenCLaP：多领域开源中文预训练语言模型仓库、UER：基于不同语料+编码器+目标任务的中文预训练模型仓库、中文自然语言处理向量合集、基于金融-司法领域(兼有闲聊性质)的聊天机器人、g2pC：基于上下文的汉语读音自动标记模块、Zincbase 知识图谱构建工具包、诗歌质量评价/细粒度情感诗歌语料库、快速转化「中文数字」和「阿拉伯数字」、百度知道问答语料库、基于知识图谱的问答系统、jieba_fast 加速版的jieba、正则表达式教程、中文阅读理解数据集、基于BERT等最新语言模型的抽取式摘要提取、Python利用深度学习进行文本摘要的综合指南、知识图谱深度学习相关资料整理、维基大规模平行文本语料、StanfordNLP 0.2.0：纯Python版自然语言处理包、NeuralNLP-NeuralClassifier：腾讯开源深度学习文本分类工具、端到端的封闭域对话系统、中文命名实体识别：NeuroNER vs. BertNER、新闻事件线索抽取、2019年百度的三元组抽取比赛：“科学空间队”源码、基于依存句法的开放域文本知识三元组抽取和知识库构建、中文的GPT2训练代码、ML-NLP - 机器学习(Machine Learning)NLP面试中常考到的知识点和代码实现、nlp4han:中文自然语言处理工具集(断句/分词/词性标注/组块/句法分析/语义分析/NER/N元语法/HMM/代词消解/情感分析/拼写检查、XLM：Facebook的跨语言预训练语言模型、用基于BERT的微调和特征提取方法来进行知识图谱百度百科人物词条属性抽取、中文自然语言处理相关的开放任务-数据集-当前最佳结果、CoupletAI - 基于CNN+Bi-LSTM+Attention 的自动对对联系统、抽象知识图谱、MiningZhiDaoQACorpus - 580万百度知道问答数据挖掘项目、brat rapid annotation tool: 序列标注工具、大规模中文知识图谱数据：1.4亿实体、数据增强在机器翻译及其他nlp任务中的应用及效果、allennlp阅读理解:支持多种数据和模型、PDF表格数据提取工具 、 Graphbrain：AI开源软件库和科研工具，目的是促进自动意义提取和文本理解以及知识的探索和推断、简历自动筛选系统、基于命名实体识别的简历自动摘要、中文语言理解测评基准，包括代表性的数据集&基准模型&语料库&排行榜、树洞 OCR 文字识别 、从包含表格的扫描图片中识别表格和文字、语声迁移、Python口语自然语言处理工具集(英文)、 similarity：相似度计算工具包，java编写、海量中文预训练ALBERT模型 、Transformers 2.0 、基于大规模音频数据集Audioset的音频增强 、Poplar：网页版自然语言标注工具、图片文字去除，可用于漫画翻译 、186种语言的数字叫法库、Amazon发布基于知识的人-人开放领域对话数据集 、中文文本纠错模块代码、繁简体转换 、 Python实现的多种文本可读性评价指标、类似于人名/地名/组织机构名的命名体识别数据集 、东南大学《知识图谱》研究生课程(资料)、. 英文拼写检查库 、 wwsearch是企业微信后台自研的全文检索引擎、CHAMELEON：深度学习新闻推荐系统元架构 、 8篇论文梳理BERT相关模型进展与反思、DocSearch：免费文档搜索引擎、 LIDA：轻量交互式对话标注工具 、aili - the fastest in-memory index in the East 东半球最快并发索引 、知识图谱车音工作项目、自然语言生成资源大全 、中日韩分词库mecab的Python接口库、中文文本摘要/关键词提取、汉字字符特征提取器 (featurizer)，提取汉字的特征（发音特征、字形特征）用做深度学习的特征、中文生成任务基准测评 、中文缩写数据集、中文任务基准测评 - 代表性的数据集-基准(预训练)模型-语料库-baseline-工具包-排行榜、PySS3：面向可解释AI的SS3文本分类器机器可视化工具 、中文NLP数据集列表、COPE - 格律诗编辑程序、doccano：基于网页的开源协同多语言文本标注工具 、PreNLP：自然语言预处理库、简单的简历解析器，用来从简历中提取关键信息、用于中文闲聊的GPT2模型：GPT2-chitchat、基于检索聊天机器人多轮响应选择相关资源列表(Leaderboards、Datasets、Papers)、(Colab)抽象文本摘要实现集锦(教程 、词语拼音数据、高效模糊搜索工具、NLP数据增广资源集、微软对话机器人框架 、 GitHub Typo Corpus：大规模GitHub多语言拼写错误/语法错误数据集、TextCluster：短文本聚类预处理模块 Short text cluster、面向语音识别的中文文本规范化、BLINK：最先进的实体链接库、BertPunc：基于BERT的最先进标点修复模型、Tokenizer：快速、可定制的文本词条化库、中文语言理解测评基准，包括代表性的数据集、基准(预训练)模型、语料库、排行榜、spaCy 医学文本挖掘与信息提取 、 NLP任务示例项目代码集、 python拼写检查库、chatbot-list - 行业内关于智能客服、聊天机器人的应用和架构、算法分享和介绍、语音质量评价指标(MOSNet, BSSEval, STOI, PESQ, SRMR)、 用138GB语料训练的法文RoBERTa预训练语言模型 、BERT-NER-Pytorch：三种不同模式的BERT中文NER实验、无道词典 - 有道词典的命令行版本，支持英汉互查和在线查询、2019年NLP亮点回顾、 Chinese medical dialogue data 中文医疗对话数据集 、最好的汉字数字(中文数字)-阿拉伯数字转换工具、 基于百科知识库的中文词语多词义/义项获取与特定句子词语语义消歧、awesome-nlp-sentiment-analysis - 情感分析、情绪原因识别、评价对象和评价词抽取、LineFlow：面向所有深度学习框架的NLP数据高效加载器、中文医学NLP公开资源整理 、MedQuAD：(英文)医学问答数据集、将自然语言数字串解析转换为整数和浮点数、Transfer Learning in Natural Language Processing (NLP) 、面向语音识别的中文/英文发音辞典、Tokenizers：注重性能与多功能性的最先进分词器、CLUENER 细粒度命名实体识别 Fine Grained Named Entity Recognition、 基于BERT的中文命名实体识别、中文谣言数据库、NLP数据集/基准任务大列表、nlp相关的一些论文及代码, 包括主题模型、词向量(Word Embedding)、命名实体识别(NER)、文本分类(Text Classificatin)、文本生成(Text Generation)、文本相似性(Text Similarity)计算等，涉及到各种与nlp相关的算法，基于keras和tensorflow 、Python文本挖掘/NLP实战示例、 Blackstone：面向非结构化法律文本的spaCy pipeline和NLP模型通过同义词替换实现文本“变脸” 、中文 预训练 ELECTREA 模型: 基于对抗学习 pretrain Chinese Model 、albert-chinese-ner - 用预训练语言模型ALBERT做中文NER 、基于GPT2的特定主题文本生成/文本增广、开源预训练语言模型合集、多语言句向量包、编码、标记和实现：一种可控高效的文本生成方法、 英文脏话大列表 、attnvis：GPT2、BERT等transformer语言模型注意力交互可视化、CoVoST：Facebook发布的多语种语音-文本翻译语料库，包括11种语言(法语、德语、荷兰语、俄语、西班牙语、意大利语、土耳其语、波斯语、瑞典语、蒙古语和中文)的语音、文字转录及英文译文、Jiagu自然语言处理工具 - 以BiLSTM等模型为基础，提供知识图谱关系抽取 中文分词 词性标注 命名实体识别 情感分析 新词发现 关键词 文本摘要 文本聚类等功能、用unet实现对文档表格的自动检测，表格重建、NLP事件提取文献资源列表 、 金融领域自然语言处理研究资源大列表、CLUEDatasetSearch - 中英文NLP数据集：搜索所有中文NLP数据集，附常用英文NLP数据集 、medical_NER - 中文医学知识图谱命名实体识别 、(哈佛)讲因果推理的免费书、知识图谱相关学习资料/数据集/工具资源大列表、Forte：灵活强大的自然语言处理pipeline工具集 、Python字符串相似性算法库、PyLaia：面向手写文档分析的深度学习工具包、TextFooler：针对文本分类/推理的对抗文本生成模块、Haystack：灵活、强大的可扩展问答(QA)框架、中文关键短语抽取工具",
        "category": "tutorial",
        "source": "github",
        "repo": "fighting41love/funNLP",
        "platform": "github",
        "tags": [],
        "metadata": {'stars': 78463, 'updated_at': '2026-01-15T17:22:16Z', 'quality_score': 70.0, 'quality_details': {'source': 100.0, 'relevance': 0.0, 'freshness': 100.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://github.com/modelcontextprotocol/servers",
        "name": "servers",
        "description": "Model Context Protocol Servers",
        "category": "other",
        "source": "github",
        "repo": "modelcontextprotocol/servers",
        "platform": "github",
        "tags": [],
        "metadata": {'stars': 76315, 'updated_at': '2026-01-15T19:40:38Z', 'quality_score': 70.0, 'quality_details': {'source': 100.0, 'relevance': 0.0, 'freshness': 100.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://github.com/mlabonne/llm-course",
        "name": "llm-course",
        "description": "Course to get into Large Language Models (LLMs) with roadmaps and Colab notebooks.",
        "category": "tutorial",
        "source": "github",
        "repo": "mlabonne/llm-course",
        "platform": "github",
        "tags": ['course', 'large-language-models', 'llm', 'machine-learning', 'roadmap'],
        "metadata": {'stars': 73137, 'updated_at': '2026-01-15T19:46:18Z', 'quality_score': 70.0, 'quality_details': {'source': 100.0, 'relevance': 0.0, 'freshness': 100.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://github.com/AntonOsika/gpt-engineer",
        "name": "gpt-engineer",
        "description": "CLI platform to experiment with codegen. Precursor to: https://lovable.dev",
        "category": "other",
        "source": "github",
        "repo": "AntonOsika/gpt-engineer",
        "platform": "github",
        "tags": ['ai', 'autonomous-agent', 'code-generation', 'codebase-generation', 'codegen', 'coding-assistant', 'gpt-4', 'gpt-engineer', 'openai', 'python'],
        "metadata": {'stars': 55187, 'updated_at': '2026-01-15T19:17:47Z', 'quality_score': 70.0, 'quality_details': {'source': 100.0, 'relevance': 0.0, 'freshness': 100.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://github.com/1c7/chinese-independent-developer",
        "name": "chinese-independent-developer",
        "description": "👩🏿‍💻👨🏾‍💻👩🏼‍💻👨🏽‍💻👩🏻‍💻中国独立开发者项目列表 -- 分享大家都在做什么",
        "category": "other",
        "source": "github",
        "repo": "1c7/chinese-independent-developer",
        "platform": "github",
        "tags": ['china', 'indie', 'indie-developer'],
        "metadata": {'stars': 46211, 'updated_at': '2026-01-15T15:13:28Z', 'quality_score': 70.0, 'quality_details': {'source': 100.0, 'relevance': 0.0, 'freshness': 100.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://github.com/GitHubDaily/GitHubDaily",
        "name": "GitHubDaily",
        "description": "坚持分享 GitHub 上高质量、有趣实用的开源技术教程、开发者工具、编程网站、技术资讯。A list cool, interesting projects of GitHub.",
        "category": "tutorial",
        "source": "github",
        "repo": "GitHubDaily/GitHubDaily",
        "platform": "github",
        "tags": ['ai', 'algorithms-and-data-structures', 'backend', 'developer-tools', 'development', 'frontend', 'github', 'java', 'javascript', 'kubernetes', 'linux', 'markdown', 'open-source', 'python', 'tutorials', 'web'],
        "metadata": {'stars': 44488, 'updated_at': '2026-01-15T18:52:49Z', 'quality_score': 70.0, 'quality_details': {'source': 100.0, 'relevance': 0.0, 'freshness': 100.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://mitchellh.com/writing/prompt-engineering-vs-blind-prompting",
        "name": "Prompt engineering vs. blind prompting",
        "description": "",
        "category": "other",
        "source": "hackernews",
        "repo": "",
        "platform": "web",
        "tags": ['prompt'],
        "metadata": {'points': 358, 'created_at': '2023-04-22T16:44:32Z', 'quality_score': 67.5, 'quality_details': {'source': 70.0, 'relevance': 75, 'freshness': 20.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://thenameless.net/astral-kit/anthropic-peit-00",
        "name": "A web version of Anthropic's prompt engineering interactive tutorial",
        "description": "",
        "category": "tutorial",
        "source": "hackernews",
        "repo": "",
        "platform": "web",
        "tags": ['prompt'],
        "metadata": {'points': 144, 'created_at': '2024-05-17T23:16:58Z', 'quality_score': 67.0, 'quality_details': {'source': 65.0, 'relevance': 75, 'freshness': 40.0, 'activity': 85.0}},
        "is_active": True,
    },
    {
        "url": "https://github.com/asgeirtj/system_prompts_leaks/blob/main/claude.txt",
        "name": "Claude's system prompt is over 24k tokens with tools",
        "description": "",
        "category": "tool",
        "source": "hackernews",
        "repo": "asgeirtj/system_prompts_leaks",
        "platform": "github",
        "tags": ['claude', 'prompt'],
        "metadata": {'points': 627, 'created_at': '2025-05-06T20:39:35Z', 'quality_score': 62.0, 'quality_details': {'source': 100.0, 'relevance': 0.0, 'freshness': 60.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://simonwillison.net/2025/May/25/claude-4-system-prompt/",
        "name": "Highlights from the Claude 4 system prompt",
        "description": "",
        "category": "other",
        "source": "hackernews",
        "repo": "",
        "platform": "web",
        "tags": ['claude', 'prompt'],
        "metadata": {'points': 309, 'created_at': '2025-05-26T21:25:56Z', 'quality_score': 62.0, 'quality_details': {'source': 100.0, 'relevance': 0.0, 'freshness': 60.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://exopriors.com/scry",
        "name": "Show HN: Use Claude Code to Query 600 GB Indexes over Hacker News, ArXiv, etc.",
        "description": "Paste in my prompt to Claude Code with an embedded API key for accessing my public readonly SQL+vector database, and you have a state-of-the-art research tool over Hacker News, arXiv, LessWrong, and dozens of other high-quality public commons sites. Claude whips up the monster SQL queries that safely run on my machine, to answer your most nuanced questions.<p>There&#x27;s also an Alerts functionality, where you can just ask Claude to submit a SQL query as an alert, and you&#x27;ll be emailed when the ultra nuanced criteria is met (and the output changes). Like I want to know when somebody posts about &quot;estrogen&quot; in a psychoactive context, or enough biology metaphors when talking about building infrastructure.<p>Currently have embedded:  posts: 1.4M &#x2F; 4.6M comments: 15.6M &#x2F; 38M That&#x27;s with Voyage-3.5-lite. And you can do amazing compositional vector search, like search @FTX_crisis - (@guilt_tone - @guilt_topic) to find writing that was about the FTX crisis and distinctly without guilty tones, but that can mention &quot;guilt&quot;.<p>I can embed everything and all the other sources for cheap, I just literally don&#x27;t have the money.",
        "category": "tool",
        "source": "hackernews",
        "repo": "",
        "platform": "web",
        "tags": ['claude', 'prompt', 'ai'],
        "metadata": {'points': 397, 'created_at': '2025-12-31T07:47:44Z', 'quality_score': 61.0, 'quality_details': {'source': 70.0, 'relevance': 0.0, 'freshness': 100.0, 'activity': 100.0}},
        "is_active": True,
    },
]
