# rag_frameworks 领域 URL 资源 - 自动生成
from typing import Any

RAW_RAG_FRAMEWORKS_URLS: list[dict[str, Any]] = [
    {
        "url": "https://github.com/stanfordnlp/dspy",
        "name": "dspy",
        "description": "DSPy: The framework for programming—not prompting—language models",
        "category": "framework",
        "source": "github",
        "repo": "stanfordnlp/dspy",
        "platform": "github",
        "tags": ['dspy'],
        "metadata": {'stars': 31551, 'updated_at': '2026-01-16T00:38:40Z', 'quality_score': 97.0, 'quality_details': {'source': 100.0, 'relevance': 90, 'freshness': 100.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://github.com/langchain-ai/langchain",
        "name": "langchain",
        "description": "🦜🔗 The platform for reliable agents.",
        "category": "framework",
        "source": "github",
        "repo": "langchain-ai/langchain",
        "platform": "github",
        "tags": ['langchain'],
        "metadata": {'stars': 124289, 'updated_at': '2026-01-16T00:34:21Z', 'quality_score': 92.5, 'quality_details': {'source': 100.0, 'relevance': 75, 'freshness': 100.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://github.com/infiniflow/ragflow",
        "name": "ragflow",
        "description": "RAGFlow is a leading open-source Retrieval-Augmented Generation (RAG) engine that fuses cutting-edge RAG with Agent capabilities to create a superior context layer for LLMs",
        "category": "other",
        "source": "github",
        "repo": "infiniflow/ragflow",
        "platform": "github",
        "tags": ['rag'],
        "metadata": {'stars': 71518, 'updated_at': '2026-01-16T00:54:12Z', 'quality_score': 92.5, 'quality_details': {'source': 100.0, 'relevance': 75, 'freshness': 100.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://github.com/mirth/chonky",
        "name": "Show HN: Chonky – a neural approach for text semantic chunking",
        "description": "TLDR: I’ve made a transformer model and a wrapper library that segments text into meaningful semantic chunks.<p>The current text splitting approaches rely on heuristics (although one can use neural embedder to group semantically related sentences).<p>I propose a fully neural approach to semantic chunking.<p>I took the base distilbert model and trained it on a bookcorpus to split concatenated text paragraphs into original paragraphs. Basically it’s a token classification task. Model fine-tuning t",
        "category": "chunking",
        "source": "hackernews",
        "repo": "mirth/chonky",
        "platform": "github",
        "tags": ['rag', 'chunking'],
        "metadata": {'points': 169, 'created_at': '2025-04-11T12:18:39Z', 'quality_score': 89.0, 'quality_details': {'source': 100.0, 'relevance': 100.0, 'freshness': 60.0, 'activity': 85.0}},
        "is_active": True,
    },
    {
        "url": "https://github.com/langmanus/langmanus",
        "name": "LangManus: An Open-Source Manus Agent with LangChain + LangGraph",
        "description": "",
        "category": "framework",
        "source": "hackernews",
        "repo": "langmanus/langmanus",
        "platform": "github",
        "tags": ['langgraph', 'langchain'],
        "metadata": {'points': 127, 'created_at': '2025-03-21T11:01:00Z', 'quality_score': 89.0, 'quality_details': {'source': 100.0, 'relevance': 100.0, 'freshness': 60.0, 'activity': 85.0}},
        "is_active": True,
    },
    {
        "url": "https://github.com/Shubhamsaboo/awesome-llm-apps",
        "name": "awesome-llm-apps",
        "description": "Collection of awesome LLM apps with AI Agents and RAG using OpenAI, Anthropic, Gemini and opensource models.",
        "category": "other",
        "source": "github",
        "repo": "Shubhamsaboo/awesome-llm-apps",
        "platform": "github",
        "tags": ['rag'],
        "metadata": {'stars': 87943, 'updated_at': '2026-01-15T23:37:52Z', 'quality_score': 86.5, 'quality_details': {'source': 100.0, 'relevance': 55, 'freshness': 100.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://github.com/fighting41love/funNLP",
        "name": "funNLP",
        "description": "中英文敏感词、语言检测、中外手机/电话归属地/运营商查询、名字推断性别、手机号抽取、身份证抽取、邮箱抽取、中日文人名库、中文缩写库、拆字词典、词汇情感值、停用词、反动词表、暴恐词表、繁简体转换、英文模拟中文发音、汪峰歌词生成器、职业名称词库、同义词库、反义词库、否定词库、汽车品牌词库、汽车零件词库、连续英文切割、各种中文词向量、公司名字大全、古诗词库、IT词库、财经词库、成语词库、地名词库、历史名人词库、诗词词库、医学词库、饮食词库、法律词库、汽车词库、动物词库、中文聊天语料、中文谣言数据、百度中文问答数据集、句子相似度匹配算法集合、bert资源、文本生成&摘要相关工具、cocoNLP信息抽取工具、国内电话号码正则匹配、清华大学XLORE:中英文跨语言百科知识图谱、清华大学人工智能技术系列报告、自然语言生成、NLU太难了系列、自动对联数据及机器人、用户名黑名单列表、罪名法务名词及分类模型、微信公众号语料、cs224n深度学习自然语言处理课程、中文手写汉字识别、中文自然语言处理 语料/数据集、变量命名神器、分词语料库+代码、任务型对话英文数据集、ASR 语音数据集 + 基于深度学习的中文",
        "category": "framework",
        "source": "github",
        "repo": "fighting41love/funNLP",
        "platform": "github",
        "tags": ['haystack'],
        "metadata": {'stars': 78465, 'updated_at': '2026-01-15T22:34:01Z', 'quality_score': 86.5, 'quality_details': {'source': 100.0, 'relevance': 55, 'freshness': 100.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://github.com/pathwaycom/pathway",
        "name": "pathway",
        "description": "Python ETL framework for stream processing, real-time analytics, LLM pipelines, and RAG.",
        "category": "other",
        "source": "github",
        "repo": "pathwaycom/pathway",
        "platform": "github",
        "tags": ['rag'],
        "metadata": {'stars': 57146, 'updated_at': '2026-01-15T21:32:11Z', 'quality_score': 86.5, 'quality_details': {'source': 100.0, 'relevance': 55, 'freshness': 100.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://github.com/pathwaycom/llm-app",
        "name": "llm-app",
        "description": "Ready-to-run cloud templates for RAG, AI pipelines, and enterprise search with live data. 🐳Docker-friendly.⚡Always in sync with Sharepoint, Google Drive, S3, Kafka, PostgreSQL, real-time data APIs, and more.",
        "category": "other",
        "source": "github",
        "repo": "pathwaycom/llm-app",
        "platform": "github",
        "tags": ['rag'],
        "metadata": {'stars': 53847, 'updated_at': '2026-01-15T21:08:02Z', 'quality_score': 86.5, 'quality_details': {'source': 100.0, 'relevance': 55, 'freshness': 100.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://github.com/run-llama/llama_index",
        "name": "llama_index",
        "description": "LlamaIndex is the leading framework for building LLM-powered agents over your data.",
        "category": "framework",
        "source": "github",
        "repo": "run-llama/llama_index",
        "platform": "github",
        "tags": ['llamaindex'],
        "metadata": {'stars': 46347, 'updated_at': '2026-01-16T00:36:05Z', 'quality_score': 86.5, 'quality_details': {'source': 100.0, 'relevance': 55, 'freshness': 100.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://github.com/langfuse/langfuse",
        "name": "langfuse",
        "description": "🪢 Open source LLM engineering platform: LLM Observability, metrics, evals, prompt management, playground, datasets. Integrates with OpenTelemetry, Langchain, OpenAI SDK, LiteLLM, and more. 🍊YC W23 ",
        "category": "framework",
        "source": "github",
        "repo": "langfuse/langfuse",
        "platform": "github",
        "tags": ['langchain'],
        "metadata": {'stars': 20585, 'updated_at': '2026-01-16T00:50:50Z', 'quality_score': 86.5, 'quality_details': {'source': 100.0, 'relevance': 55, 'freshness': 100.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://github.com/truefoundry/cognita",
        "name": "Show HN: Cognita – open-source RAG framework for modular applications",
        "description": "Hey HN, exciting news! Our RAG framework, Cognita (<a href=\"https:&#x2F;&#x2F;github.com&#x2F;truefoundry&#x2F;cognita\">https:&#x2F;&#x2F;github.com&#x2F;truefoundry&#x2F;cognita</a>), born from collaborations with diverse enterprises, is now open-source. Currently, it offers seamless integrations with Qdrant and SingleStore.<p>In recent weeks, numerous engineers have explored Cognita, providing invaluable insights and feedback. We deeply appreciate your input and encourage ongoing dialogue (sha",
        "category": "framework",
        "source": "hackernews",
        "repo": "truefoundry/cognita",
        "platform": "github",
        "tags": ['rag', 'langchain', 'llamaindex'],
        "metadata": {'points': 142, 'created_at': '2024-04-27T16:40:06Z', 'quality_score': 85.0, 'quality_details': {'source': 100.0, 'relevance': 100.0, 'freshness': 40.0, 'activity': 85.0}},
        "is_active": True,
    },
    {
        "url": "https://github.com/bhavnicksm/chonkie",
        "name": "Show HN: Chonkie – A Fast, Lightweight Text Chunking Library for RAG",
        "description": "I built Chonkie because I was tired of rewriting chunking code for RAG applications. Existing libraries were either too bloated (80MB+) or too basic, with no middle ground.<p>Core features:<p>- 21MB default install vs 80-171MB alternatives<p>- 33x faster token chunking than popular alternatives<p>- Supports multiple chunking strategies: token, word, sentence, and semantic<p>- Works with all major tokenizers (transformers, tokenizers, tiktoken)<p>- Zero external dependencies for basic functionali",
        "category": "chunking",
        "source": "hackernews",
        "repo": "bhavnicksm/chonkie",
        "platform": "github",
        "tags": ['rag', 'chunking'],
        "metadata": {'points': 199, 'created_at': '2024-11-10T15:58:25Z', 'quality_score': 85.0, 'quality_details': {'source': 100.0, 'relevance': 100.0, 'freshness': 40.0, 'activity': 85.0}},
        "is_active": True,
    },
    {
        "url": "https://github.com/OpenSPG/KAG",
        "name": "KAG – Knowledge Graph RAG Framework",
        "description": "",
        "category": "other",
        "source": "hackernews",
        "repo": "OpenSPG/KAG",
        "platform": "github",
        "tags": ['rag'],
        "metadata": {'points': 230, 'created_at': '2024-12-30T02:55:58Z', 'quality_score': 85.0, 'quality_details': {'source': 100.0, 'relevance': 90, 'freshness': 40.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://github.com/SciPhi-AI/R2R",
        "name": "Show HN: R2R – Open-source framework for production-grade RAG",
        "description": "Hello HN, I&#x27;m Owen from SciPhi (<a href=\"https:&#x2F;&#x2F;www.sciphi.ai&#x2F;\" rel=\"nofollow\">https:&#x2F;&#x2F;www.sciphi.ai&#x2F;</a>), a startup working on simplifying˛Retrieval-Augmented Generation (RAG). Today we’re excited to share R2R (<a href=\"https:&#x2F;&#x2F;github.com&#x2F;SciPhi-AI&#x2F;R2R\">https:&#x2F;&#x2F;github.com&#x2F;SciPhi-AI&#x2F;R2R</a>), an open-source framework that makes it simpler to develop and deploy production-grade RAG systems.<p>Just a quick reminder: RAG h",
        "category": "chunking",
        "source": "hackernews",
        "repo": "SciPhi-AI/R2R",
        "platform": "github",
        "tags": ['rag', 'chunking'],
        "metadata": {'points': 167, 'created_at': '2024-02-26T13:10:13Z', 'quality_score': 85.0, 'quality_details': {'source': 100.0, 'relevance': 100.0, 'freshness': 40.0, 'activity': 85.0}},
        "is_active": True,
    },
    {
        "url": "https://github.com/inkeep/agents",
        "name": "Show HN: Inkeep (YC W23) – Agent Builder to create agents in code or visually",
        "description": "Hi HN! I&#x27;m Nick from Inkeep. We built an agent builder with true 2-way sync between code and a drag-and-drop visual editor, so devs and non-devs can collaborate on the same agents. Here’s a demo video: <a href=\"https:&#x2F;&#x2F;go.inkeep.com&#x2F;video\">https:&#x2F;&#x2F;go.inkeep.com&#x2F;video</a>.<p>As a developer, the flow is: 1) Build AI Chat Assistants or AI Workflows with the TypeScript SDK 2) Run `inkeep push` from your CLI to publish 3)Edit agents in the visual builder (or hand of",
        "category": "framework",
        "source": "hackernews",
        "repo": "inkeep/agents",
        "platform": "github",
        "tags": ['rag', 'langgraph'],
        "metadata": {'points': 79, 'created_at': '2025-10-16T12:50:08Z', 'quality_score': 84.5, 'quality_details': {'source': 100.0, 'relevance': 85, 'freshness': 75.0, 'activity': 70.0}},
        "is_active": True,
    },
    {
        "url": "https://blog.abdellatif.io/production-rag-processing-5m-documents",
        "name": "Production RAG: what I learned from processing 5M+ documents",
        "description": "",
        "category": "other",
        "source": "hackernews",
        "repo": "",
        "platform": "web",
        "tags": ['rag'],
        "metadata": {'points': 551, 'created_at': '2025-10-20T15:55:36Z', 'quality_score': 81.5, 'quality_details': {'source': 70.0, 'relevance': 75, 'freshness': 90.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://blog.yakkomajuri.com/blog/local-rag",
        "name": "So you wanna build a local RAG?",
        "description": "",
        "category": "other",
        "source": "hackernews",
        "repo": "",
        "platform": "web",
        "tags": ['rag'],
        "metadata": {'points': 390, 'created_at': '2025-11-28T16:54:56Z', 'quality_score': 81.5, 'quality_details': {'source': 70.0, 'relevance': 75, 'freshness': 90.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://github.com/NeumTry/NeumAI",
        "name": "Show HN: Neum AI – Open-source large-scale RAG framework",
        "description": "Over the last couple months we have been supporting developers in building large-scale RAG pipelines to process millions of pieces of data.<p>We documented our approach in an HN post (<a href=\"https:&#x2F;&#x2F;news.ycombinator.com&#x2F;item?id=37824547\">https:&#x2F;&#x2F;news.ycombinator.com&#x2F;item?id=37824547</a>) a couple weeks ago. Today, we are open sourcing the framework we have developed.<p>The framework focuses on RAG data pipelines and provides scale, reliability, and data synchroniz",
        "category": "chunking",
        "source": "hackernews",
        "repo": "NeumTry/NeumAI",
        "platform": "github",
        "tags": ['rag', 'chunking'],
        "metadata": {'points': 155, 'created_at': '2023-11-21T19:20:29Z', 'quality_score': 81.0, 'quality_details': {'source': 100.0, 'relevance': 100.0, 'freshness': 20.0, 'activity': 85.0}},
        "is_active": True,
    },
    {
        "url": "https://github.com/circlemind-ai/fast-graphrag",
        "name": "Show HN: FastGraphRAG – Better RAG using good old PageRank",
        "description": "Hey there HN! We’re Antonio, Luca, and Yuhang, and we’re excited to introduce Fast GraphRAG, an open-source RAG approach that leverages knowledge graphs and the 25 years old PageRank for better information retrieval and reasoning.<p>Building a good RAG pipeline these days takes a lot of manual optimizations. Most engineers intuitively start from naive RAG: throw everything in a vector database and hope that semantic search is powerful enough. This can work for use cases where accuracy isn’t too ",
        "category": "tutorial",
        "source": "hackernews",
        "repo": "circlemind-ai/fast-graphrag",
        "platform": "github",
        "tags": ['rag'],
        "metadata": {'points': 457, 'created_at': '2024-11-18T17:43:13Z', 'quality_score': 80.5, 'quality_details': {'source': 100.0, 'relevance': 75, 'freshness': 40.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://github.com/haystackeditor/haystack-editor",
        "name": "Launch HN: Haystack (YC S24) – Visualize and edit code on an infinite canvas",
        "description": "Hi HN, we’re Akshay and Jake from Haystack (<a href=\"https:&#x2F;&#x2F;haystackeditor.com&#x2F;\">https:&#x2F;&#x2F;haystackeditor.com&#x2F;</a>). Haystack re-imagines the IDE by putting it on a 2D digital whiteboard that automatically draws connections between code as you navigate and edit files. We designed it to match our mental model of how code works – as a graph of connected components. Here’s a demo of what it looks like: <a href=\"https:&#x2F;&#x2F;www.youtube.com&#x2F;watch?v=5XADctpWNNs\"",
        "category": "framework",
        "source": "hackernews",
        "repo": "haystackeditor/haystack-editor",
        "platform": "github",
        "tags": ['haystack'],
        "metadata": {'points': 328, 'created_at': '2024-09-25T15:31:00Z', 'quality_score': 80.5, 'quality_details': {'source': 100.0, 'relevance': 75, 'freshness': 40.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://github.com/pipecat-ai/pipecat",
        "name": "Show HN: An open source framework for voice assistants",
        "description": "I&#x27;ve been obsessed for the past ~year with the possibilities of talking to LLMs. I built a bunch of one-off prototypes, shared code on X, started a Meetup group in SF, and co-hosted a big hackathon. It turns out that there are a few low-level problems that everybody building conversational&#x2F;real-time AI needs to solve on the way to building&#x2F;shipping something that works well: low-latency media transport, echo cancellation, voice activity detection, phrase endpointing, pipelining da",
        "category": "framework",
        "source": "hackernews",
        "repo": "pipecat-ai/pipecat",
        "platform": "github",
        "tags": ['langchain', 'llamaindex'],
        "metadata": {'points': 346, 'created_at': '2024-05-13T17:21:14Z', 'quality_score': 79.0, 'quality_details': {'source': 100.0, 'relevance': 70, 'freshness': 40.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://github.com/hwchase17/langgraph-engineer",
        "name": "LangGraph Engineer",
        "description": "",
        "category": "framework",
        "source": "hackernews",
        "repo": "hwchase17/langgraph-engineer",
        "platform": "github",
        "tags": ['langgraph'],
        "metadata": {'points': 63, 'created_at': '2024-08-09T16:28:43Z', 'quality_score': 79.0, 'quality_details': {'source': 100.0, 'relevance': 90, 'freshness': 40.0, 'activity': 70.0}},
        "is_active": True,
    },
    {
        "url": "https://github.com/llmware-ai/llmware",
        "name": "Show HN: LLMWare – Small Specialized Function Calling 1B LLMs for Multi-Step RAG",
        "description": "Hi, I was a corporate lawyer for many years working with a lot of financial services and insurance companies. In practicing law, I noticed there was a lot of repetition in the tasks I was working on even as a highly paid attorney that could be automated.<p>I wanted to solve the problem of dealing with a lot information and data in a practical way, using AI. This motivated me to start AI Bloks&#x2F;LLMWare with my husband, who had a deep background in software and is a very early adopter of AI.<p",
        "category": "other",
        "source": "hackernews",
        "repo": "llmware-ai/llmware",
        "platform": "github",
        "tags": ['rag'],
        "metadata": {'points': 51, 'created_at': '2024-02-11T14:40:26Z', 'quality_score': 79.0, 'quality_details': {'source': 100.0, 'relevance': 90, 'freshness': 40.0, 'activity': 70.0}},
        "is_active": True,
    },
    {
        "url": "https://paddedinputs.substack.com/p/meta-superintelligences-surprising",
        "name": "Meta Superintelligence Labs' first paper is about RAG",
        "description": "<a href=\"https:&#x2F;&#x2F;arxiv.org&#x2F;abs&#x2F;2509.01092\" rel=\"nofollow\">https:&#x2F;&#x2F;arxiv.org&#x2F;abs&#x2F;2509.01092</a>",
        "category": "other",
        "source": "hackernews",
        "repo": "",
        "platform": "web",
        "tags": ['rag'],
        "metadata": {'points': 423, 'created_at': '2025-10-11T23:16:05Z', 'quality_score': 78.5, 'quality_details': {'source': 70.0, 'relevance': 75, 'freshness': 75.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://github.com/mastra-ai/mastra",
        "name": "Show HN: Mastra – Open-source JS agent framework, by the developers of Gatsby",
        "description": "Hi HN, we’re Sam, Shane, and Abhi, and we’re building Mastra (<a href=\"https:&#x2F;&#x2F;mastra.ai\">https:&#x2F;&#x2F;mastra.ai</a>), an open-source JavaScript SDK for building agents on top of Vercel’s AI SDK.<p>You can start a Mastra project with `npm create mastra` and create workflow graphs that can suspend&#x2F;resume, build a RAG pipeline and write evals, give agents memory, create multi-agent workflows, and view it all in a local playground.<p>Previously, we built Gatsby, the open-source ",
        "category": "tutorial",
        "source": "hackernews",
        "repo": "mastra-ai/mastra",
        "platform": "github",
        "tags": ['rag'],
        "metadata": {'points': 442, 'created_at': '2025-02-19T15:25:08Z', 'quality_score': 78.5, 'quality_details': {'source': 100.0, 'relevance': 55, 'freshness': 60.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://github.com/pchunduri6/rag-demystified",
        "name": "Show HN: Demystifying Advanced RAG Pipelines",
        "description": "I&#x27;ve built an advanced RAG (Retrieval-Augmented Generation) pipeline from scratch to demystify the complex mechanics of modern LLM-powered Question Answering systems. This repository features:<p>-- An implementation of a sub-question query engine from scratch to answer complex user questions.<p>-- Illustrative explanations that unveil the inner workings of the system.<p>-- An analysis of the challenges I faced while working with the system, like prompt engineering and cost estimation.<p>-- ",
        "category": "framework",
        "source": "hackernews",
        "repo": "pchunduri6/rag-demystified",
        "platform": "github",
        "tags": ['rag', 'llamaindex'],
        "metadata": {'points': 131, 'created_at': '2023-10-28T15:01:34Z', 'quality_score': 78.0, 'quality_details': {'source': 100.0, 'relevance': 90, 'freshness': 20.0, 'activity': 85.0}},
        "is_active": True,
    },
    {
        "url": "https://github.com/psychic-api/rag-stack",
        "name": "Show HN: RAGstack – private ChatGPT for enterprise VPCs, built with Llama 2",
        "description": "Hey hacker news,<p>We’re the cofounders at Psychic.dev (<a href=\"http:&#x2F;&#x2F;psychic.dev\">http:&#x2F;&#x2F;psychic.dev</a>) where we help companies connect LLMs to private data. With the launch of Llama 2, we think it’s finally viable to self-host an internal application that’s on-par with ChatGPT, so we did exactly that and made it an open source project.<p>We also included a vector DB and API server so you can upload files and connect Llama 2 to your own data.<p>The RAG in RAGstack stands",
        "category": "framework",
        "source": "hackernews",
        "repo": "psychic-api/rag-stack",
        "platform": "github",
        "tags": ['rag', 'langchain'],
        "metadata": {'points': 84, 'created_at': '2023-07-20T17:11:08Z', 'quality_score': 78.0, 'quality_details': {'source': 100.0, 'relevance': 100.0, 'freshness': 20.0, 'activity': 70.0}},
        "is_active": True,
    },
    {
        "url": "https://github.com/hwchase17/langchain",
        "name": "LangChain: Build AI apps with LLMs through composability",
        "description": "",
        "category": "framework",
        "source": "hackernews",
        "repo": "hwchase17/langchain",
        "platform": "github",
        "tags": ['langchain'],
        "metadata": {'points': 372, 'created_at': '2023-01-18T02:16:13Z', 'quality_score': 76.5, 'quality_details': {'source': 100.0, 'relevance': 75, 'freshness': 20.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://github.com/Forethought-Technologies/AutoChain",
        "name": "AutoChain, lightweight and testable alternative to LangChain",
        "description": "",
        "category": "framework",
        "source": "hackernews",
        "repo": "Forethought-Technologies/AutoChain",
        "platform": "github",
        "tags": ['langchain'],
        "metadata": {'points': 211, 'created_at': '2023-07-18T16:47:53Z', 'quality_score': 76.5, 'quality_details': {'source': 100.0, 'relevance': 75, 'freshness': 20.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://github.com/lmnr-ai/flow",
        "name": "Show HN: Flow – A dynamic task engine for building AI agents",
        "description": "I think graph is a wrong abstraction for building AI agents. Just look at how incredibly hard it is to make routing using LangGraph - conditional edges are a mess.<p>I built Laminar Flow to solve a common frustration with traditional workflow engines - the rigid need to predefine all node connections. Instead of static DAGs, Flow uses a dynamic task queue system that lets workflows evolve at runtime.<p>Flow is built on 3 core principles:<p>* Concurrent Execution - Tasks run in parallel automatic",
        "category": "framework",
        "source": "hackernews",
        "repo": "lmnr-ai/flow",
        "platform": "github",
        "tags": ['langgraph'],
        "metadata": {'points': 160, 'created_at': '2024-12-02T18:51:03Z', 'quality_score': 76.0, 'quality_details': {'source': 100.0, 'relevance': 70, 'freshness': 40.0, 'activity': 85.0}},
        "is_active": True,
    },
    {
        "url": "https://www.microsoft.com/en-us/research/blog/graphrag-new-tool-for-complex-data-discovery-now-on-github/",
        "name": "GraphRAG is now on GitHub",
        "description": "The team at Microsoft is pleased to announce that GraphRAG is now available in open-source!<p>Check out the announcement video: <a href=\"https:&#x2F;&#x2F;youtu.be&#x2F;dsesHoTXyk0\" rel=\"nofollow\">https:&#x2F;&#x2F;youtu.be&#x2F;dsesHoTXyk0</a><p>GraphRAG is a research project from Microsoft exploring the use of knowledge graphs and large language models for enhanced retrieval augmented generation. It is an end-to-end system for richly understanding text-heavy datasets by combining text extracti",
        "category": "other",
        "source": "hackernews",
        "repo": "",
        "platform": "web",
        "tags": ['rag'],
        "metadata": {'points': 282, 'created_at': '2024-07-02T14:41:19Z', 'quality_score': 76.0, 'quality_details': {'source': 70.0, 'relevance': 90, 'freshness': 40.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://www.daemonology.net/blog/chunking-attacks.pdf",
        "name": "Chunking Attacks on File Backup Services Using Content-Deﬁned Chunking [pdf]",
        "description": "",
        "category": "chunking",
        "source": "hackernews",
        "repo": "",
        "platform": "web",
        "tags": ['chunking'],
        "metadata": {'points': 123, 'created_at': '2025-03-21T17:30:34Z', 'quality_score': 75.5, 'quality_details': {'source': 65.0, 'relevance': 90, 'freshness': 60.0, 'activity': 85.0}},
        "is_active": True,
    },
    {
        "url": "https://stackoverflow.blog/2024/06/06/breaking-up-is-hard-to-do-chunking-in-rag-applications/",
        "name": "Breaking up is hard to do: Chunking in RAG applications",
        "description": "",
        "category": "chunking",
        "source": "hackernews",
        "repo": "",
        "platform": "web",
        "tags": ['rag', 'chunking'],
        "metadata": {'points': 143, 'created_at': '2024-06-08T08:14:54Z', 'quality_score': 74.5, 'quality_details': {'source': 65.0, 'relevance': 100.0, 'freshness': 40.0, 'activity': 85.0}},
        "is_active": True,
    },
    {
        "url": "https://github.com/Mintplex-Labs/anything-llm",
        "name": "Show HN: AnythingLLM – Open-Source, All-in-One Desktop AI Assistant",
        "description": "Hey HN!<p>This is Tim from AnythingLLM (<a href=\"https:&#x2F;&#x2F;github.com&#x2F;Mintplex-Labs&#x2F;anything-llm\">https:&#x2F;&#x2F;github.com&#x2F;Mintplex-Labs&#x2F;anything-llm</a>). AnythingLLM is an open-source desktop assistant that brings together RAG (Retrieval-Augmented Generation), agents, embeddings, vector databases, and more—all in one seamless package.<p>We built AnythingLLM over the last year iterating and iterating from user feedback. Our primary mission is to enable people wit",
        "category": "other",
        "source": "hackernews",
        "repo": "Mintplex-Labs/anything-llm",
        "platform": "github",
        "tags": ['rag'],
        "metadata": {'points': 368, 'created_at': '2024-09-05T15:40:45Z', 'quality_score': 74.5, 'quality_details': {'source': 100.0, 'relevance': 55, 'freshness': 40.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://github.com/paulpierre/RasaGPT",
        "name": "RasaGPT: First headless LLM chatbot built on top of Rasa, Langchain and FastAPI",
        "description": "",
        "category": "framework",
        "source": "hackernews",
        "repo": "paulpierre/RasaGPT",
        "platform": "github",
        "tags": ['langchain'],
        "metadata": {'points': 179, 'created_at': '2023-05-08T08:31:37Z', 'quality_score': 73.5, 'quality_details': {'source': 100.0, 'relevance': 75, 'freshness': 20.0, 'activity': 85.0}},
        "is_active": True,
    },
    {
        "url": "https://github.com/deepset-ai/haystack",
        "name": "Haystack 1.0 – open-source NLP framework to build NLProc back end applications",
        "description": "",
        "category": "framework",
        "source": "hackernews",
        "repo": "deepset-ai/haystack",
        "platform": "github",
        "tags": ['haystack'],
        "metadata": {'points': 109, 'created_at': '2021-12-09T18:27:24Z', 'quality_score': 73.5, 'quality_details': {'source': 100.0, 'relevance': 75, 'freshness': 20.0, 'activity': 85.0}},
        "is_active": True,
    },
    {
        "url": "https://airbyte.com/tutorials/chat-with-your-data-using-openai-pinecone-airbyte-and-langchain",
        "name": "Show HN: Chat with your data using LangChain, Pinecone, and Airbyte",
        "description": "Hi HN,<p>A few of our team members at Airbyte (and Joe, who killed it!) recently played with building our own internal support chat bot, using Airbyte, Langchain, Pinecone and OpenAI, that would answer any questions we ask when developing a new connector on Airbyte.<p>As we prototyped it, we realized that it could be applied for many other use cases and sources of data, so... we created a tutorial that other community members can leverage [<a href=\"http:&#x2F;&#x2F;airbyte.com&#x2F;tutorials&#x2",
        "category": "framework",
        "source": "hackernews",
        "repo": "",
        "platform": "web",
        "tags": ['rag', 'langchain'],
        "metadata": {'points': 220, 'created_at': '2023-08-08T15:32:13Z', 'quality_score': 72.0, 'quality_details': {'source': 70.0, 'relevance': 90, 'freshness': 20.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://www.octomind.dev/blog/why-we-no-longer-use-langchain-for-building-our-ai-agents",
        "name": "Why we no longer use LangChain for building our AI agents",
        "description": "",
        "category": "framework",
        "source": "hackernews",
        "repo": "",
        "platform": "web",
        "tags": ['langchain'],
        "metadata": {'points': 480, 'created_at': '2024-06-20T15:41:56Z', 'quality_score': 71.5, 'quality_details': {'source': 70.0, 'relevance': 75, 'freshness': 40.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://haystackeditor.com/",
        "name": "Show HN: Haystack – an IDE for exploring and editing code on an infinite canvas",
        "description": "Hi HN, we’re building Haystack Editor (<a href=\"https:&#x2F;&#x2F;haystackeditor.com&#x2F;\" rel=\"nofollow\">https:&#x2F;&#x2F;haystackeditor.com&#x2F;</a>), a canvas-based IDE that automates the boring stuff (plumbing, refactoring, and finding code) so that you can focus on the exciting parts of software development! You can see a quick overview of Haystack at <a href=\"https:&#x2F;&#x2F;www.youtube.com&#x2F;watch?v=c2uZnR5D_cc\" rel=\"nofollow\">https:&#x2F;&#x2F;www.youtube.com&#x2F;watch?v=c2uZnR5",
        "category": "framework",
        "source": "hackernews",
        "repo": "",
        "platform": "web",
        "tags": ['haystack'],
        "metadata": {'points': 546, 'created_at': '2024-07-25T13:54:14Z', 'quality_score': 71.5, 'quality_details': {'source': 70.0, 'relevance': 75, 'freshness': 40.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://dspy.ai/",
        "name": "DSPy – Programming–not prompting–LMs",
        "description": "",
        "category": "framework",
        "source": "hackernews",
        "repo": "",
        "platform": "web",
        "tags": ['dspy'],
        "metadata": {'points': 189, 'created_at': '2024-12-06T19:59:49Z', 'quality_score': 71.5, 'quality_details': {'source': 65.0, 'relevance': 90, 'freshness': 40.0, 'activity': 85.0}},
        "is_active": True,
    },
    {
        "url": "https://www.pi.website/research/real_time_chunking",
        "name": "Real-time action chunking with large models",
        "description": "",
        "category": "chunking",
        "source": "hackernews",
        "repo": "",
        "platform": "web",
        "tags": ['chunking'],
        "metadata": {'points': 84, 'created_at': '2025-06-17T19:39:26Z', 'quality_score': 71.0, 'quality_details': {'source': 60.0, 'relevance': 90, 'freshness': 60.0, 'activity': 70.0}},
        "is_active": True,
    },
    {
        "url": "https://www.qodo.ai/blog/why-we-chose-langgraph-to-build-our-coding-agent/",
        "name": "We chose LangGraph to build our coding agent",
        "description": "",
        "category": "framework",
        "source": "hackernews",
        "repo": "",
        "platform": "web",
        "tags": ['langgraph'],
        "metadata": {'points': 83, 'created_at': '2025-03-25T05:50:36Z', 'quality_score': 71.0, 'quality_details': {'source': 60.0, 'relevance': 90, 'freshness': 60.0, 'activity': 70.0}},
        "is_active": True,
    },
    {
        "url": "https://rivet.ironcladapp.com/",
        "name": "Show HN: Rivet – open-source AI Agent dev env with real-world applications",
        "description": "We just launched Rivet, the open-source visual AI programming environment! We built Rivet, because we were building complex AI Agent applications at Ironclad. It unlocked our abilities here, and we&#x27;re excited to make available to the entire community.<p>Backstory: A few months ago, inspired by things like LangChain and LlamaIndex, we started building an AI agent that could work with legal contracts. Unfortunately, we couldn&#x27;t just use retrieval augmented generation (RAG), because a lot",
        "category": "framework",
        "source": "hackernews",
        "repo": "",
        "platform": "web",
        "tags": ['rag', 'langchain', 'llamaindex'],
        "metadata": {'points': 176, 'created_at': '2023-09-08T13:29:05Z', 'quality_score': 70.5, 'quality_details': {'source': 65.0, 'relevance': 100.0, 'freshness': 20.0, 'activity': 85.0}},
        "is_active": True,
    },
    {
        "url": "https://www.bloomberg.com/opinion/articles/2021-01-27/gamestop-short-squeeze-is-rage-against-the-financial-machine",
        "name": "GameStop Is Rage Against the Financial Machine",
        "description": "",
        "category": "other",
        "source": "hackernews",
        "repo": "",
        "platform": "web",
        "tags": ['rag'],
        "metadata": {'points': 1078, 'created_at': '2021-01-27T16:29:45Z', 'quality_score': 67.5, 'quality_details': {'source': 70.0, 'relevance': 75, 'freshness': 20.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://craphound.com/news/2018/07/02/mark-zuckerberg-and-his-empire-of-oily-rags/",
        "name": "Mark Zuckerberg and his empire of oily rags",
        "description": "",
        "category": "other",
        "source": "hackernews",
        "repo": "",
        "platform": "web",
        "tags": ['rag'],
        "metadata": {'points': 417, 'created_at': '2018-07-06T13:36:38Z', 'quality_score': 67.5, 'quality_details': {'source': 70.0, 'relevance': 75, 'freshness': 20.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://www.protocol.com/policy/w3c-privacy-war",
        "name": "A privacy war is raging inside the W3C",
        "description": "",
        "category": "other",
        "source": "hackernews",
        "repo": "",
        "platform": "web",
        "tags": ['rag'],
        "metadata": {'points': 376, 'created_at': '2021-07-13T19:54:18Z', 'quality_score': 67.5, 'quality_details': {'source': 70.0, 'relevance': 75, 'freshness': 20.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://www.ragya.com/",
        "name": "Ragya – Indian classical music played by time of the day",
        "description": "",
        "category": "other",
        "source": "hackernews",
        "repo": "",
        "platform": "web",
        "tags": ['rag'],
        "metadata": {'points': 341, 'created_at': '2020-11-26T18:25:13Z', 'quality_score': 67.5, 'quality_details': {'source': 70.0, 'relevance': 75, 'freshness': 20.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "http://www.npr.org/blogs/krulwich/2011/03/18/134597833/cosmonaut-crashed-into-earth-crying-in-rage?ft=1&f=1026",
        "name": "Cosmonaut Crashed Into Earth 'Crying In Rage' [in 1967]",
        "description": "",
        "category": "other",
        "source": "hackernews",
        "repo": "",
        "platform": "web",
        "tags": ['rag'],
        "metadata": {'points': 339, 'created_at': '2011-03-19T01:19:21Z', 'quality_score': 67.5, 'quality_details': {'source': 70.0, 'relevance': 75, 'freshness': 20.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://www.llamaindex.ai/",
        "name": "LlamaIndex: Unleash the power of LLMs over your data",
        "description": "",
        "category": "framework",
        "source": "hackernews",
        "repo": "",
        "platform": "web",
        "tags": ['llamaindex'],
        "metadata": {'points': 208, 'created_at': '2023-07-08T04:39:39Z', 'quality_score': 67.5, 'quality_details': {'source': 70.0, 'relevance': 75, 'freshness': 20.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://old.reddit.com/r/LangChain/comments/13fcw36/langchain_is_pointless/",
        "name": "Langchain Is Pointless",
        "description": "",
        "category": "framework",
        "source": "hackernews",
        "repo": "",
        "platform": "web",
        "tags": ['langchain'],
        "metadata": {'points': 386, 'created_at': '2023-07-08T15:56:19Z', 'quality_score': 67.5, 'quality_details': {'source': 70.0, 'relevance': 75, 'freshness': 20.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://minimaxir.com/2023/07/langchain-problem/",
        "name": "The Problem with LangChain",
        "description": "",
        "category": "framework",
        "source": "hackernews",
        "repo": "",
        "platform": "web",
        "tags": ['langchain'],
        "metadata": {'points': 268, 'created_at': '2023-07-14T16:11:09Z', 'quality_score': 67.5, 'quality_details': {'source': 70.0, 'relevance': 75, 'freshness': 20.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://blog.scottlogic.com/2023/05/04/langchain-mini.html",
        "name": "Re-implementing LangChain in 100 lines of code",
        "description": "",
        "category": "framework",
        "source": "hackernews",
        "repo": "",
        "platform": "web",
        "tags": ['langchain'],
        "metadata": {'points': 252, 'created_at': '2023-05-04T19:33:12Z', 'quality_score': 67.5, 'quality_details': {'source': 70.0, 'relevance': 75, 'freshness': 20.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://blog.langchain.dev/announcing-our-10m-seed-round-led-by-benchmark/",
        "name": "LangChain Announces 10M Seed Round",
        "description": "",
        "category": "framework",
        "source": "hackernews",
        "repo": "",
        "platform": "web",
        "tags": ['langchain'],
        "metadata": {'points': 235, 'created_at': '2023-04-04T16:48:00Z', 'quality_score': 67.5, 'quality_details': {'source': 70.0, 'relevance': 75, 'freshness': 20.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://blog.langchain.dev/retrieval/",
        "name": "Retrieval in LangChain",
        "description": "",
        "category": "framework",
        "source": "hackernews",
        "repo": "",
        "platform": "web",
        "tags": ['langchain'],
        "metadata": {'points': 212, 'created_at': '2023-03-25T12:21:39Z', 'quality_score': 67.5, 'quality_details': {'source': 70.0, 'relevance': 75, 'freshness': 20.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "http://www.newyorker.com/magazine/2015/01/26/whole-haystack",
        "name": "The Whole Haystack: The N.S.A. claims it needs access to all our phone records",
        "description": "",
        "category": "framework",
        "source": "hackernews",
        "repo": "",
        "platform": "web",
        "tags": ['haystack'],
        "metadata": {'points': 247, 'created_at': '2015-01-19T16:41:06Z', 'quality_score': 67.5, 'quality_details': {'source': 70.0, 'relevance': 75, 'freshness': 20.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://www.kuriositas.com/2013/09/the-art-of-romanian-haystack.html",
        "name": "The Art of the Romanian Haystack",
        "description": "",
        "category": "framework",
        "source": "hackernews",
        "repo": "",
        "platform": "web",
        "tags": ['haystack'],
        "metadata": {'points': 228, 'created_at': '2021-07-14T22:19:47Z', 'quality_score': 67.5, 'quality_details': {'source': 70.0, 'relevance': 75, 'freshness': 20.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://haystack.deepset.ai/blog/introducing-haystack-agents",
        "name": "Introducing Agents in Haystack: Make LLMs resolve complex tasks",
        "description": "",
        "category": "framework",
        "source": "hackernews",
        "repo": "",
        "platform": "web",
        "tags": ['haystack'],
        "metadata": {'points': 202, 'created_at': '2023-04-03T19:47:26Z', 'quality_score': 67.5, 'quality_details': {'source': 70.0, 'relevance': 75, 'freshness': 20.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://docs.sweep.dev/blogs/chunking-2m-files",
        "name": "Chunking 2M files a day for code search using syntax trees",
        "description": "",
        "category": "chunking",
        "source": "hackernews",
        "repo": "",
        "platform": "web",
        "tags": ['chunking'],
        "metadata": {'points': 168, 'created_at': '2023-07-31T20:35:13Z', 'quality_score': 67.5, 'quality_details': {'source': 65.0, 'relevance': 90, 'freshness': 20.0, 'activity': 85.0}},
        "is_active": True,
    },
    {
        "url": "http://www.bbc.co.uk/news/magazine-11258175",
        "name": "Chunking & Gridding - Why parents can't do math today",
        "description": "",
        "category": "chunking",
        "source": "hackernews",
        "repo": "",
        "platform": "web",
        "tags": ['chunking'],
        "metadata": {'points': 123, 'created_at': '2010-09-10T15:27:03Z', 'quality_score': 67.5, 'quality_details': {'source': 65.0, 'relevance': 90, 'freshness': 20.0, 'activity': 85.0}},
        "is_active": True,
    },
    {
        "url": "https://github.com/axilla-io/ax",
        "name": "Show HN: Axilla – Open-source TypeScript framework for LLM apps",
        "description": "Hi HN, we are Nick and Ben, creators of Axilla - an open source TypeScript framework to develop LLM applications. It’s in the early stages but you can use it today: we’ve already published 2 modules and have more coming soon.<p>Ben and I met while working at Cruise on the ML platform for self-driving cars. We spent many years there and learned the hard way that shipping AI is not quite the same as shipping regular code. There are many parts of the ML lifecycle, e.g., mining, processing, and labe",
        "category": "tutorial",
        "source": "hackernews",
        "repo": "axilla-io/ax",
        "platform": "github",
        "tags": ['rag'],
        "metadata": {'points': 161, 'created_at': '2023-08-07T14:00:38Z', 'quality_score': 67.5, 'quality_details': {'source': 100.0, 'relevance': 55, 'freshness': 20.0, 'activity': 85.0}},
        "is_active": True,
    },
    {
        "url": "https://arxiv.org/abs/2406.19292",
        "name": "Artificial needles to real haystacks: Improving retrieval capabilities in LLMs",
        "description": "",
        "category": "framework",
        "source": "hackernews",
        "repo": "",
        "platform": "web",
        "tags": ['haystack'],
        "metadata": {'points': 101, 'created_at': '2024-06-29T04:55:57Z', 'quality_score': 67.0, 'quality_details': {'source': 65.0, 'relevance': 75, 'freshness': 40.0, 'activity': 85.0}},
        "is_active": True,
    },
    {
        "url": "https://blog.isaacmiller.dev/posts/dspy",
        "name": "Betting on DSPy for Systems of LLMs",
        "description": "",
        "category": "framework",
        "source": "hackernews",
        "repo": "",
        "platform": "web",
        "tags": ['dspy'],
        "metadata": {'points': 83, 'created_at': '2024-08-11T02:11:47Z', 'quality_score': 67.0, 'quality_details': {'source': 60.0, 'relevance': 90, 'freshness': 40.0, 'activity': 70.0}},
        "is_active": True,
    },
    {
        "url": "https://quilt.fly.dev/",
        "name": "Show HN: Quilt – Powerful RAG UI for Document QA",
        "description": "Hey HN! We&#x27;ve just launched Quilt, a robust RAG (Retrieval-Augmented Generation) UI that revolutionizes how you interact with your documents.<p>Key features: - Multi-user setup with private&#x2F;public document collections - Advanced hybrid RAG pipeline combining full-text &amp; vector search - Smart citations with in-browser PDF preview and highlights - Fully customizable settings and prompts through the UI<p>Making an account is free, no need to even use a strong password: this is only to",
        "category": "other",
        "source": "hackernews",
        "repo": "",
        "platform": "web",
        "tags": ['rag'],
        "metadata": {'points': 63, 'created_at': '2024-10-02T03:54:07Z', 'quality_score': 67.0, 'quality_details': {'source': 60.0, 'relevance': 90, 'freshness': 40.0, 'activity': 70.0}},
        "is_active": True,
    },
    {
        "url": "http://37signals.com/svn/posts/1976-launch-haystack-a-better-way-for-web-designers-to-find-clients-and-for-clients-to-find-web-designers",
        "name": "37signals Launches Haystack for Web Designers and Clients To Find Each Other",
        "description": "",
        "category": "framework",
        "source": "hackernews",
        "repo": "",
        "platform": "web",
        "tags": ['haystack'],
        "metadata": {'points': 134, 'created_at': '2009-10-21T20:06:37Z', 'quality_score': 63.0, 'quality_details': {'source': 65.0, 'relevance': 75, 'freshness': 20.0, 'activity': 85.0}},
        "is_active": True,
    },
    {
        "url": "https://nullprogram.com/blog/2019/12/09/",
        "name": "Chunking Optimizations: Let the Knife Do the Work",
        "description": "",
        "category": "chunking",
        "source": "hackernews",
        "repo": "",
        "platform": "web",
        "tags": ['chunking'],
        "metadata": {'points': 83, 'created_at': '2019-12-09T22:51:42Z', 'quality_score': 63.0, 'quality_details': {'source': 60.0, 'relevance': 90, 'freshness': 20.0, 'activity': 70.0}},
        "is_active": True,
    },
    {
        "url": "https://ochagavia.nl/blog/chunking-strings-in-elixir-how-difficult-can-it-be/",
        "name": "Chunking strings in Elixir: how difficult can it be?",
        "description": "",
        "category": "chunking",
        "source": "hackernews",
        "repo": "",
        "platform": "web",
        "tags": ['chunking'],
        "metadata": {'points': 80, 'created_at': '2023-01-04T15:18:45Z', 'quality_score': 63.0, 'quality_details': {'source': 60.0, 'relevance': 90, 'freshness': 20.0, 'activity': 70.0}},
        "is_active": True,
    },
    {
        "url": "https://docs.sweep.dev/blogs/sweeps-core-algo",
        "name": "Using Retrieval Augmented Generation (RAG) to clear our GitHub backlog",
        "description": "",
        "category": "other",
        "source": "hackernews",
        "repo": "",
        "platform": "web",
        "tags": ['rag'],
        "metadata": {'points': 52, 'created_at': '2023-08-10T20:07:50Z', 'quality_score': 63.0, 'quality_details': {'source': 60.0, 'relevance': 90, 'freshness': 20.0, 'activity': 70.0}},
        "is_active": True,
    },
    {
        "url": "https://devv.ai",
        "name": "Show HN: I made a better Perplexity for developers",
        "description": "Hi HN,<p>I am Jiayuan, and I&#x27;m here to introduce a tool we&#x27;ve been building over the past few months: Devv (<a href=\"https:&#x2F;&#x2F;devv.ai\" rel=\"nofollow\">https:&#x2F;&#x2F;devv.ai</a>). In simple terms, it is an AI-powered search engine specifically designed for developers.<p>Now, you might ask, with so many AI search engines already available—Perplexity, You.com, Phind, and several open-source projects—why do we need another one?<p>We all know that Generative Search Engines are b",
        "category": "other",
        "source": "hackernews",
        "repo": "",
        "platform": "web",
        "tags": ['rag'],
        "metadata": {'points': 185, 'created_at': '2024-05-08T15:19:40Z', 'quality_score': 61.0, 'quality_details': {'source': 65.0, 'relevance': 55, 'freshness': 40.0, 'activity': 85.0}},
        "is_active": True,
    },
]
