# llm_providers 领域 URL 资源 - 官方 SDK 仓库
from typing import Any

RAW_LLM_PROVIDERS_URLS: list[dict[str, Any]] = [
    {
        "url": "https://github.com/openai/openai-python",
        "name": "openai-python",
        "description": "OpenAI Python SDK",
        "category": "sdk",
        "source": "official",
        "repo": "openai/openai-python",
        "platform": "github",
        "tags": ['openai'],
        "metadata": {
            "provider": "openai",
            "provider_name": "OpenAI",
            "company": "OpenAI",
            "country": "🇺🇸 美国",
            "console_url": "https://platform.openai.com/api-keys",
            "docs_url": "https://platform.openai.com/docs",
            "free_tier": "无免费额度，需充值",
            "env_key": "OPENAI_API_KEY",
            "stars": 29684,
            "updated_at": "2026-01-16T21:31:02Z",
        },
        "is_active": True,
    },
    {
        "url": "https://github.com/openai/openai-node",
        "name": "openai-node",
        "description": "OpenAI Node.js SDK",
        "category": "sdk",
        "source": "official",
        "repo": "openai/openai-node",
        "platform": "github",
        "tags": ['openai'],
        "metadata": {
            "provider": "openai",
            "provider_name": "OpenAI",
            "company": "OpenAI",
            "country": "🇺🇸 美国",
            "console_url": "https://platform.openai.com/api-keys",
            "docs_url": "https://platform.openai.com/docs",
            "free_tier": "无免费额度，需充值",
            "env_key": "OPENAI_API_KEY",
            "stars": 10541,
            "updated_at": "2026-01-16T18:40:53Z",
        },
        "is_active": True,
    },
    {
        "url": "https://github.com/anthropics/anthropic-sdk-python",
        "name": "anthropic-sdk-python",
        "description": "Anthropic Python SDK",
        "category": "sdk",
        "source": "official",
        "repo": "anthropics/anthropic-sdk-python",
        "platform": "github",
        "tags": ['anthropic'],
        "metadata": {
            "provider": "anthropic",
            "provider_name": "Anthropic",
            "company": "Anthropic",
            "country": "🇺🇸 美国",
            "console_url": "https://console.anthropic.com/settings/keys",
            "docs_url": "https://docs.anthropic.com/",
            "free_tier": "$5 免费额度（需验证手机）",
            "env_key": "ANTHROPIC_API_KEY",
            "stars": 2627,
            "updated_at": "2026-01-16T11:36:43Z",
        },
        "is_active": True,
    },
    {
        "url": "https://github.com/anthropics/anthropic-sdk-typescript",
        "name": "anthropic-sdk-typescript",
        "description": "Anthropic TypeScript SDK",
        "category": "sdk",
        "source": "official",
        "repo": "anthropics/anthropic-sdk-typescript",
        "platform": "github",
        "tags": ['anthropic'],
        "metadata": {
            "provider": "anthropic",
            "provider_name": "Anthropic",
            "company": "Anthropic",
            "country": "🇺🇸 美国",
            "console_url": "https://console.anthropic.com/settings/keys",
            "docs_url": "https://docs.anthropic.com/",
            "free_tier": "$5 免费额度（需验证手机）",
            "env_key": "ANTHROPIC_API_KEY",
            "stars": 1518,
            "updated_at": "2026-01-16T11:36:45Z",
        },
        "is_active": True,
    },
    {
        "url": "https://github.com/google-gemini/generative-ai-python",
        "name": "generative-ai-python",
        "description": "Google Generative AI Python SDK",
        "category": "sdk",
        "source": "official",
        "repo": "google-gemini/generative-ai-python",
        "platform": "github",
        "tags": ['gemini'],
        "metadata": {
            "provider": "gemini",
            "provider_name": "Google Gemini",
            "company": "Google",
            "country": "🇺🇸 美国",
            "console_url": "https://aistudio.google.com/apikey",
            "docs_url": "https://ai.google.dev/docs",
            "free_tier": "免费，15 RPM / 1M tokens/day",
            "env_key": "GEMINI_API_KEY",
            "stars": 2261,
            "updated_at": "2026-01-16T02:31:01Z",
        },
        "is_active": True,
    },
    {
        "url": "https://github.com/google-gemini/generative-ai-js",
        "name": "generative-ai-js",
        "description": "Google Generative AI JS SDK",
        "category": "sdk",
        "source": "official",
        "repo": "google-gemini/generative-ai-js",
        "platform": "github",
        "tags": ['gemini'],
        "metadata": {
            "provider": "gemini",
            "provider_name": "Google Gemini",
            "company": "Google",
            "country": "🇺🇸 美国",
            "console_url": "https://aistudio.google.com/apikey",
            "docs_url": "https://ai.google.dev/docs",
            "free_tier": "免费，15 RPM / 1M tokens/day",
            "env_key": "GEMINI_API_KEY",
            "stars": 1238,
            "updated_at": "2026-01-15T13:37:26Z",
        },
        "is_active": True,
    },
    {
        "url": "https://github.com/xai-org/grok-1",
        "name": "grok-1",
        "description": "xAI Grok-1 开源模型",
        "category": "sdk",
        "source": "official",
        "repo": "xai-org/grok-1",
        "platform": "github",
        "tags": ['xai'],
        "metadata": {
            "provider": "xai",
            "provider_name": "xAI (Grok)",
            "company": "xAI",
            "country": "🇺🇸 美国",
            "console_url": "https://console.x.ai/",
            "docs_url": "https://docs.x.ai/",
            "free_tier": "$25/月 免费额度（Beta期间）",
            "env_key": "XAI_API_KEY",
            "stars": 50580,
            "updated_at": "2026-01-16T19:01:31Z",
        },
        "is_active": True,
    },
    {
        "url": "https://github.com/xai-org/grok-prompts",
        "name": "grok-prompts",
        "description": "xAI Grok 系统提示词",
        "category": "sdk",
        "source": "official",
        "repo": "xai-org/grok-prompts",
        "platform": "github",
        "tags": ['xai'],
        "metadata": {
            "provider": "xai",
            "provider_name": "xAI (Grok)",
            "company": "xAI",
            "country": "🇺🇸 美国",
            "console_url": "https://console.x.ai/",
            "docs_url": "https://docs.x.ai/",
            "free_tier": "$25/月 免费额度（Beta期间）",
            "env_key": "XAI_API_KEY",
            "stars": 3793,
            "updated_at": "2026-01-16T02:17:48Z",
        },
        "is_active": True,
    },
    {
        "url": "https://github.com/groq/groq-python",
        "name": "groq-python",
        "description": "Groq Python SDK",
        "category": "sdk",
        "source": "official",
        "repo": "groq/groq-python",
        "platform": "github",
        "tags": ['groq'],
        "metadata": {
            "provider": "groq",
            "provider_name": "Groq",
            "company": "Groq",
            "country": "🇺🇸 美国",
            "console_url": "https://console.groq.com/keys",
            "docs_url": "https://console.groq.com/docs",
            "free_tier": "免费，有速率限制",
            "env_key": "GROQ_API_KEY",
            "stars": 572,
            "updated_at": "2026-01-13T08:35:28Z",
        },
        "is_active": True,
    },
    {
        "url": "https://github.com/groq/groq-typescript",
        "name": "groq-typescript",
        "description": "Groq TypeScript SDK",
        "category": "sdk",
        "source": "official",
        "repo": "groq/groq-typescript",
        "platform": "github",
        "tags": ['groq'],
        "metadata": {
            "provider": "groq",
            "provider_name": "Groq",
            "company": "Groq",
            "country": "🇺🇸 美国",
            "console_url": "https://console.groq.com/keys",
            "docs_url": "https://console.groq.com/docs",
            "free_tier": "免费，有速率限制",
            "env_key": "GROQ_API_KEY",
            "stars": 237,
            "updated_at": "2026-01-10T14:58:36Z",
        },
        "is_active": True,
    },
    {
        "url": "https://github.com/mistralai/client-python",
        "name": "client-python",
        "description": "Mistral AI Python SDK",
        "category": "sdk",
        "source": "official",
        "repo": "mistralai/client-python",
        "platform": "github",
        "tags": ['mistral'],
        "metadata": {
            "provider": "mistral",
            "provider_name": "Mistral AI",
            "company": "Mistral AI",
            "country": "🇫🇷 法国",
            "console_url": "https://console.mistral.ai/api-keys",
            "docs_url": "https://docs.mistral.ai/",
            "free_tier": "Experiment 计划免费",
            "env_key": "MISTRAL_API_KEY",
            "stars": 685,
            "updated_at": "2026-01-16T09:18:22Z",
        },
        "is_active": True,
    },
    {
        "url": "https://github.com/mistralai/client-ts",
        "name": "client-ts",
        "description": "Mistral AI TypeScript SDK",
        "category": "sdk",
        "source": "official",
        "repo": "mistralai/client-ts",
        "platform": "github",
        "tags": ['mistral'],
        "metadata": {
            "provider": "mistral",
            "provider_name": "Mistral AI",
            "company": "Mistral AI",
            "country": "🇫🇷 法国",
            "console_url": "https://console.mistral.ai/api-keys",
            "docs_url": "https://docs.mistral.ai/",
            "free_tier": "Experiment 计划免费",
            "env_key": "MISTRAL_API_KEY",
            "stars": 117,
            "updated_at": "2026-01-16T09:35:59Z",
        },
        "is_active": True,
    },
    {
        "url": "https://github.com/cohere-ai/cohere-python",
        "name": "cohere-python",
        "description": "Cohere Python SDK",
        "category": "sdk",
        "source": "official",
        "repo": "cohere-ai/cohere-python",
        "platform": "github",
        "tags": ['cohere'],
        "metadata": {
            "provider": "cohere",
            "provider_name": "Cohere",
            "company": "Cohere",
            "country": "🇨🇦 加拿大",
            "console_url": "https://dashboard.cohere.com/api-keys",
            "docs_url": "https://docs.cohere.com/",
            "free_tier": "Trial key 免费",
            "env_key": "COHERE_API_KEY",
            "stars": 378,
            "updated_at": "2026-01-04T06:00:58Z",
        },
        "is_active": True,
    },
    {
        "url": "https://github.com/cohere-ai/cohere-typescript",
        "name": "cohere-typescript",
        "description": "Cohere TypeScript SDK",
        "category": "sdk",
        "source": "official",
        "repo": "cohere-ai/cohere-typescript",
        "platform": "github",
        "tags": ['cohere'],
        "metadata": {
            "provider": "cohere",
            "provider_name": "Cohere",
            "company": "Cohere",
            "country": "🇨🇦 加拿大",
            "console_url": "https://dashboard.cohere.com/api-keys",
            "docs_url": "https://docs.cohere.com/",
            "free_tier": "Trial key 免费",
            "env_key": "COHERE_API_KEY",
            "stars": 160,
            "updated_at": "2025-11-25T15:35:02Z",
        },
        "is_active": True,
    },
    {
        "url": "https://github.com/AI21Labs/ai21-python",
        "name": "ai21-python",
        "description": "AI21 Labs Python SDK",
        "category": "sdk",
        "source": "official",
        "repo": "AI21Labs/ai21-python",
        "platform": "github",
        "tags": ['ai21'],
        "metadata": {
            "provider": "ai21",
            "provider_name": "AI21 Labs",
            "company": "AI21 Labs",
            "country": "🇮🇱 以色列",
            "console_url": "https://studio.ai21.com/account/api-key",
            "docs_url": "https://docs.ai21.com/",
            "free_tier": "免费试用额度",
            "env_key": "AI21_API_KEY",
            "stars": 69,
            "updated_at": "2026-01-12T14:41:10Z",
        },
        "is_active": True,
    },
    {
        "url": "https://github.com/togethercomputer/together-python",
        "name": "together-python",
        "description": "Together AI Python SDK",
        "category": "sdk",
        "source": "official",
        "repo": "togethercomputer/together-python",
        "platform": "github",
        "tags": ['together'],
        "metadata": {
            "provider": "together",
            "provider_name": "Together AI",
            "company": "Together AI",
            "country": "🇺🇸 美国",
            "console_url": "https://api.together.xyz/settings/api-keys",
            "docs_url": "https://docs.together.ai/",
            "free_tier": "$5 免费额度",
            "env_key": "TOGETHER_API_KEY",
            "stars": 79,
            "updated_at": "2026-01-09T14:13:46Z",
        },
        "is_active": True,
    },
    {
        "url": "https://github.com/fw-ai-external/python-sdk",
        "name": "python-sdk",
        "description": "Fireworks AI Python SDK",
        "category": "sdk",
        "source": "official",
        "repo": "fw-ai-external/python-sdk",
        "platform": "github",
        "tags": ['fireworks'],
        "metadata": {
            "provider": "fireworks",
            "provider_name": "Fireworks AI",
            "company": "Fireworks AI",
            "country": "🇺🇸 美国",
            "console_url": "https://fireworks.ai/api-keys",
            "docs_url": "https://docs.fireworks.ai/",
            "free_tier": "$1 免费额度",
            "env_key": "FIREWORKS_API_KEY",
            "stars": 4,
            "updated_at": "2026-01-16T20:50:11Z",
        },
        "is_active": True,
    },
    {
        "url": "https://github.com/replicate/replicate-python",
        "name": "replicate-python",
        "description": "Replicate Python SDK",
        "category": "sdk",
        "source": "official",
        "repo": "replicate/replicate-python",
        "platform": "github",
        "tags": ['replicate'],
        "metadata": {
            "provider": "replicate",
            "provider_name": "Replicate",
            "company": "Replicate",
            "country": "🇺🇸 美国",
            "console_url": "https://replicate.com/account/api-tokens",
            "docs_url": "https://replicate.com/docs",
            "free_tier": "$10 免费额度",
            "env_key": "REPLICATE_API_TOKEN",
            "stars": 887,
            "updated_at": "2026-01-16T04:24:26Z",
        },
        "is_active": True,
    },
    {
        "url": "https://github.com/replicate/replicate-javascript",
        "name": "replicate-javascript",
        "description": "Replicate JavaScript SDK",
        "category": "sdk",
        "source": "official",
        "repo": "replicate/replicate-javascript",
        "platform": "github",
        "tags": ['replicate'],
        "metadata": {
            "provider": "replicate",
            "provider_name": "Replicate",
            "company": "Replicate",
            "country": "🇺🇸 美国",
            "console_url": "https://replicate.com/account/api-tokens",
            "docs_url": "https://replicate.com/docs",
            "free_tier": "$10 免费额度",
            "env_key": "REPLICATE_API_TOKEN",
            "stars": 591,
            "updated_at": "2026-01-12T14:43:11Z",
        },
        "is_active": True,
    },
    {
        "url": "https://github.com/huggingface/huggingface_hub",
        "name": "huggingface_hub",
        "description": "Hugging Face Hub Python SDK",
        "category": "sdk",
        "source": "official",
        "repo": "huggingface/huggingface_hub",
        "platform": "github",
        "tags": ['huggingface'],
        "metadata": {
            "provider": "huggingface",
            "provider_name": "Hugging Face Inference",
            "company": "Hugging Face",
            "country": "🇺🇸 美国",
            "console_url": "https://huggingface.co/settings/tokens",
            "docs_url": "https://huggingface.co/docs/api-inference/",
            "free_tier": "Serverless 免费，有速率限制",
            "env_key": "HF_TOKEN",
            "stars": 3255,
            "updated_at": "2026-01-16T22:10:51Z",
        },
        "is_active": True,
    },
    {
        "url": "https://github.com/huggingface/transformers",
        "name": "transformers",
        "description": "Hugging Face Transformers",
        "category": "sdk",
        "source": "official",
        "repo": "huggingface/transformers",
        "platform": "github",
        "tags": ['huggingface'],
        "metadata": {
            "provider": "huggingface",
            "provider_name": "Hugging Face Inference",
            "company": "Hugging Face",
            "country": "🇺🇸 美国",
            "console_url": "https://huggingface.co/settings/tokens",
            "docs_url": "https://huggingface.co/docs/api-inference/",
            "free_tier": "Serverless 免费，有速率限制",
            "env_key": "HF_TOKEN",
            "stars": 155211,
            "updated_at": "2026-01-16T22:04:20Z",
        },
        "is_active": True,
    },
    {
        "url": "https://github.com/nathanrchn/perplexityai",
        "name": "perplexityai",
        "description": "Perplexity AI Python API (社区)",
        "category": "sdk",
        "source": "official",
        "repo": "nathanrchn/perplexityai",
        "platform": "github",
        "tags": ['perplexity'],
        "metadata": {
            "provider": "perplexity",
            "provider_name": "Perplexity",
            "company": "Perplexity AI",
            "country": "🇺🇸 美国",
            "console_url": "https://www.perplexity.ai/settings/api",
            "docs_url": "https://docs.perplexity.ai/",
            "free_tier": "无免费额度",
            "env_key": "PERPLEXITY_API_KEY",
            "stars": 278,
            "updated_at": "2026-01-16T14:58:32Z",
        },
        "is_active": True,
    },
    {
        "url": "https://github.com/deepseek-ai/DeepSeek-V3",
        "name": "DeepSeek-V3",
        "description": "DeepSeek V3 模型",
        "category": "sdk",
        "source": "official",
        "repo": "deepseek-ai/DeepSeek-V3",
        "platform": "github",
        "tags": ['deepseek'],
        "metadata": {
            "provider": "deepseek",
            "provider_name": "DeepSeek",
            "company": "深度求索",
            "country": "🇨🇳 中国",
            "console_url": "https://platform.deepseek.com/api_keys",
            "docs_url": "https://platform.deepseek.com/api-docs",
            "free_tier": "新用户赠送额度",
            "env_key": "DEEPSEEK_API_KEY",
            "stars": 101132,
            "updated_at": "2026-01-16T21:39:13Z",
        },
        "is_active": True,
    },
    {
        "url": "https://github.com/deepseek-ai/DeepSeek-R1",
        "name": "DeepSeek-R1",
        "description": "DeepSeek R1 推理模型",
        "category": "sdk",
        "source": "official",
        "repo": "deepseek-ai/DeepSeek-R1",
        "platform": "github",
        "tags": ['deepseek'],
        "metadata": {
            "provider": "deepseek",
            "provider_name": "DeepSeek",
            "company": "深度求索",
            "country": "🇨🇳 中国",
            "console_url": "https://platform.deepseek.com/api_keys",
            "docs_url": "https://platform.deepseek.com/api-docs",
            "free_tier": "新用户赠送额度",
            "env_key": "DEEPSEEK_API_KEY",
            "stars": 91717,
            "updated_at": "2026-01-16T21:31:52Z",
        },
        "is_active": True,
    },
    {
        "url": "https://github.com/deepseek-ai/DeepSeek-Coder-V2",
        "name": "DeepSeek-Coder-V2",
        "description": "DeepSeek Coder V2",
        "category": "sdk",
        "source": "official",
        "repo": "deepseek-ai/DeepSeek-Coder-V2",
        "platform": "github",
        "tags": ['deepseek'],
        "metadata": {
            "provider": "deepseek",
            "provider_name": "DeepSeek",
            "company": "深度求索",
            "country": "🇨🇳 中国",
            "console_url": "https://platform.deepseek.com/api_keys",
            "docs_url": "https://platform.deepseek.com/api-docs",
            "free_tier": "新用户赠送额度",
            "env_key": "DEEPSEEK_API_KEY",
            "stars": 6351,
            "updated_at": "2026-01-16T16:21:30Z",
        },
        "is_active": True,
    },
    {
        "url": "https://github.com/MoonshotAI/Kimi-K2",
        "name": "Kimi-K2",
        "description": "月之暗面 Kimi-K2 模型",
        "category": "sdk",
        "source": "official",
        "repo": "MoonshotAI/Kimi-K2",
        "platform": "github",
        "tags": ['moonshot'],
        "metadata": {
            "provider": "moonshot",
            "provider_name": "月之暗面 (Kimi)",
            "company": "月之暗面",
            "country": "🇨🇳 中国",
            "console_url": "https://platform.moonshot.cn/console/api-keys",
            "docs_url": "https://platform.moonshot.cn/docs",
            "free_tier": "新用户赠送额度",
            "env_key": "MOONSHOT_API_KEY",
            "stars": 9828,
            "updated_at": "2026-01-16T21:32:02Z",
        },
        "is_active": True,
    },
    {
        "url": "https://github.com/zhipuai/zhipuai-sdk-python-v4",
        "name": "zhipuai-sdk-python-v4",
        "description": "智谱AI Python SDK",
        "category": "sdk",
        "source": "official",
        "repo": "zhipuai/zhipuai-sdk-python-v4",
        "platform": "github",
        "tags": ['zhipu'],
        "metadata": {
            "provider": "zhipu",
            "provider_name": "智谱AI",
            "company": "智谱AI",
            "country": "🇨🇳 中国",
            "console_url": "https://open.bigmodel.cn/usercenter/apikeys",
            "docs_url": "https://open.bigmodel.cn/dev/api",
            "free_tier": "新用户赠送额度",
            "env_key": "ZHIPU_API_KEY",
            "stars": 195,
            "updated_at": "2025-12-24T09:54:23Z",
        },
        "is_active": True,
    },
    {
        "url": "https://github.com/QwenLM/Qwen2.5",
        "name": "Qwen2.5",
        "description": "通义千问 Qwen2.5",
        "category": "sdk",
        "source": "official",
        "repo": "QwenLM/Qwen2.5",
        "platform": "github",
        "tags": ['qwen'],
        "metadata": {
            "provider": "qwen",
            "provider_name": "通义千问",
            "company": "阿里云",
            "country": "🇨🇳 中国",
            "console_url": "https://dashscope.console.aliyun.com/apiKey",
            "docs_url": "https://help.aliyun.com/zh/dashscope/",
            "free_tier": "新用户赠送额度",
            "env_key": "DASHSCOPE_API_KEY",
            "stars": 26172,
            "updated_at": "2026-01-16T21:48:42Z",
        },
        "is_active": True,
    },
    {
        "url": "https://github.com/QwenLM/Qwen-Agent",
        "name": "Qwen-Agent",
        "description": "Qwen Agent 框架",
        "category": "sdk",
        "source": "official",
        "repo": "QwenLM/Qwen-Agent",
        "platform": "github",
        "tags": ['qwen'],
        "metadata": {
            "provider": "qwen",
            "provider_name": "通义千问",
            "company": "阿里云",
            "country": "🇨🇳 中国",
            "console_url": "https://dashscope.console.aliyun.com/apiKey",
            "docs_url": "https://help.aliyun.com/zh/dashscope/",
            "free_tier": "新用户赠送额度",
            "env_key": "DASHSCOPE_API_KEY",
            "stars": 12959,
            "updated_at": "2026-01-16T17:06:53Z",
        },
        "is_active": True,
    },
    {
        "url": "https://github.com/PaddlePaddle/ERNIE-SDK",
        "name": "ERNIE-SDK",
        "description": "百度文心一言 ERNIE SDK",
        "category": "sdk",
        "source": "official",
        "repo": "PaddlePaddle/ERNIE-SDK",
        "platform": "github",
        "tags": ['ernie'],
        "metadata": {
            "provider": "ernie",
            "provider_name": "百度文心一言",
            "company": "百度",
            "country": "🇨🇳 中国",
            "console_url": "https://console.bce.baidu.com/qianfan/ais/console/applicationConsole/application",
            "docs_url": "https://cloud.baidu.com/doc/WENXINWORKSHOP/",
            "free_tier": "新用户赠送额度",
            "env_key": "QIANFAN_API_KEY",
            "stars": 378,
            "updated_at": "2026-01-10T04:39:07Z",
        },
        "is_active": True,
    },
    {
        "url": "https://github.com/volcengine/volc-sdk-python",
        "name": "volc-sdk-python",
        "description": "火山引擎(豆包) Python SDK",
        "category": "sdk",
        "source": "official",
        "repo": "volcengine/volc-sdk-python",
        "platform": "github",
        "tags": ['doubao'],
        "metadata": {
            "provider": "doubao",
            "provider_name": "字节豆包",
            "company": "字节跳动",
            "country": "🇨🇳 中国",
            "console_url": "https://console.volcengine.com/ark/region:ark+cn-beijing/apiKey",
            "docs_url": "https://www.volcengine.com/docs/82379",
            "free_tier": "新用户赠送额度",
            "env_key": "ARK_API_KEY",
            "stars": 189,
            "updated_at": "2026-01-15T11:54:09Z",
        },
        "is_active": True,
    },
    {
        "url": "https://github.com/baichuan-inc/Baichuan2",
        "name": "Baichuan2",
        "description": "百川智能 Baichuan2",
        "category": "sdk",
        "source": "official",
        "repo": "baichuan-inc/Baichuan2",
        "platform": "github",
        "tags": ['baichuan'],
        "metadata": {
            "provider": "baichuan",
            "provider_name": "百川智能",
            "company": "百川智能",
            "country": "🇨🇳 中国",
            "stars": 4121,
            "updated_at": "2026-01-16T10:14:39Z",
        },
        "is_active": True,
    },
    {
        "url": "https://github.com/01-ai/Yi",
        "name": "Yi",
        "description": "零一万物 Yi 模型",
        "category": "sdk",
        "source": "official",
        "repo": "01-ai/Yi",
        "platform": "github",
        "tags": ['yi'],
        "metadata": {
            "provider": "yi",
            "provider_name": "零一万物",
            "company": "零一万物",
            "country": "🇨🇳 中国",
            "stars": 7840,
            "updated_at": "2026-01-16T03:20:25Z",
        },
        "is_active": True,
    },
    {
        "url": "https://github.com/MiniMax-AI/MiniMax-01",
        "name": "MiniMax-01",
        "description": "MiniMax-01 模型",
        "category": "sdk",
        "source": "official",
        "repo": "MiniMax-AI/MiniMax-01",
        "platform": "github",
        "tags": ['minimax'],
        "metadata": {
            "provider": "minimax",
            "provider_name": "MiniMax",
            "company": "MiniMax",
            "country": "🇨🇳 中国",
            "stars": 3297,
            "updated_at": "2026-01-16T21:31:52Z",
        },
        "is_active": True,
    },
]
