# llm_models 领域 URL 资源 - 自动生成
from typing import Any

RAW_LLM_MODELS_URLS: list[dict[str, Any]] = [
    {
        "url": "https://github.com/ollama/ollama",
        "name": "ollama",
        "description": "Get up and running with OpenAI gpt-oss, DeepSeek-R1, Gemma 3 and other models.",
        "category": "model",
        "source": "github",
        "repo": "ollama/ollama",
        "platform": "github",
        "tags": ['deepseek', 'llama', 'ollama', 'openai', 'gpt'],
        "metadata": {'stars': 159598, 'updated_at': '2026-01-16T19:31:34Z', 'quality_score': 100.0, 'quality_details': {'source': 100.0, 'relevance': 100.0, 'freshness': 100.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://github.com/open-webui/open-webui",
        "name": "open-webui",
        "description": "User-friendly AI Interface (Supports Ollama, OpenAI API, ...)",
        "category": "model",
        "source": "github",
        "repo": "open-webui/open-webui",
        "platform": "github",
        "tags": ['openai', 'llama', 'ollama'],
        "metadata": {'stars': 120890, 'updated_at': '2026-01-16T19:44:36Z', 'quality_score': 100.0, 'quality_details': {'source': 100.0, 'relevance': 100.0, 'freshness': 100.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://github.com/ggml-org/llama.cpp",
        "name": "llama.cpp",
        "description": "LLM inference in C/C++",
        "category": "model",
        "source": "github",
        "repo": "ggml-org/llama.cpp",
        "platform": "github",
        "tags": ['llama', 'llm'],
        "metadata": {'stars': 93097, 'updated_at': '2026-01-16T19:39:03Z', 'quality_score': 100.0, 'quality_details': {'source': 100.0, 'relevance': 100.0, 'freshness': 100.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://github.com/Shubhamsaboo/awesome-llm-apps",
        "name": "awesome-llm-apps",
        "description": "Collection of awesome LLM apps with AI Agents and RAG using OpenAI, Anthropic, Gemini and opensource models.",
        "category": "api",
        "source": "github",
        "repo": "Shubhamsaboo/awesome-llm-apps",
        "platform": "github",
        "tags": ['openai', 'anthropic', 'gemini', 'llm'],
        "metadata": {'stars': 88027, 'updated_at': '2026-01-16T19:19:21Z', 'quality_score': 100.0, 'quality_details': {'source': 100.0, 'relevance': 100.0, 'freshness': 100.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://github.com/fighting41love/funNLP",
        "name": "funNLP",
        "description": "中英文敏感词、语言检测、中外手机/电话归属地/运营商查询、名字推断性别、手机号抽取、身份证抽取、邮箱抽取、中日文人名库、中文缩写库、拆字词典、词汇情感值、停用词、反动词表、暴恐词表、繁简体转换、英文模拟中文发音、汪峰歌词生成器、职业名称词库、同义词库、反义词库、否定词库、汽车品牌词库、汽车零件词库、连续英文切割、各种中文词向量、公司名字大全、古诗词库、IT词库、财经词库、成语词库、地名词库、历史名人词库、诗词词库、医学词库、饮食词库、法律词库、汽车词库、动物词库、中文聊天语料、中文谣言数据、百度中文问答数据集、句子相似度匹配算法集合、bert资源、文本生成&摘要相关工具、cocoNLP信息抽取工具、国内电话号码正则匹配、清华大学XLORE:中英文跨语言百科知识图谱、清华大学人工智能技术系列报告、自然语言生成、NLU太难了系列、自动对联数据及机器人、用户名黑名单列表、罪名法务名词及分类模型、微信公众号语料、cs224n深度学习自然语言处理课程、中文手写汉字识别、中文自然语言处理 语料/数据集、变量命名神器、分词语料库+代码、任务型对话英文数据集、ASR 语音数据集 + 基于深度学习的中文",
        "category": "other",
        "source": "github",
        "repo": "fighting41love/funNLP",
        "platform": "github",
        "tags": ['transformers', 'chatbot', 'gpt'],
        "metadata": {'stars': 78484, 'updated_at': '2026-01-16T15:40:07Z', 'quality_score': 100.0, 'quality_details': {'source': 100.0, 'relevance': 100.0, 'freshness': 100.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://github.com/BerriAI/litellm",
        "name": "litellm",
        "description": "Python SDK, Proxy Server (AI Gateway) to call 100+ LLM APIs in OpenAI (or native) format, with cost tracking, guardrails, loadbalancing and logging. [Bedrock, Azure, OpenAI, VertexAI, Cohere, Anthropic, Sagemaker, HuggingFace, VLLM, NVIDIA NIM]",
        "category": "inference",
        "source": "github",
        "repo": "BerriAI/litellm",
        "platform": "github",
        "tags": ['vllm', 'llm', 'openai', 'huggingface', 'xai', 'anthropic'],
        "metadata": {'stars': 33958, 'updated_at': '2026-01-16T19:29:44Z', 'quality_score': 100.0, 'quality_details': {'source': 100.0, 'relevance': 100.0, 'freshness': 100.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://github.com/songquanpeng/one-api",
        "name": "one-api",
        "description": "LLM API 管理 & 分发系统，支持 OpenAI、Azure、Anthropic Claude、Google Gemini、DeepSeek、字节豆包、ChatGLM、文心一言、讯飞星火、通义千问、360 智脑、腾讯混元等主流模型，统一 API 适配，可用于 key 管理与二次分发。单可执行文件，提供 Docker 镜像，一键部署，开箱即用。LLM API management & key redistribution system, unifying multiple providers under a single API. Single binary, Docker-ready, with an English UI.",
        "category": "api",
        "source": "github",
        "repo": "songquanpeng/one-api",
        "platform": "github",
        "tags": ['claude', 'deepseek', 'llm', 'openai', 'gemini', 'anthropic'],
        "metadata": {'stars': 29094, 'updated_at': '2026-01-16T18:09:20Z', 'quality_score': 100.0, 'quality_details': {'source': 100.0, 'relevance': 100.0, 'freshness': 100.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://github.com/chatanywhere/GPT_API_free",
        "name": "GPT_API_free",
        "description": "Free ChatGPT&DeepSeek API Key，免费ChatGPT&DeepSeek API。免费接入DeepSeek API和GPT4 API，支持 gpt | deepseek | claude | gemini | grok 等排名靠前的常用大模型。",
        "category": "other",
        "source": "github",
        "repo": "chatanywhere/GPT_API_free",
        "platform": "github",
        "tags": ['claude', 'deepseek', 'grok', 'gemini', 'gpt'],
        "metadata": {'stars': 35582, 'updated_at': '2026-01-16T15:23:18Z', 'quality_score': 100.0, 'quality_details': {'source': 100.0, 'relevance': 100.0, 'freshness': 100.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://github.com/binary-husky/gpt_academic",
        "name": "gpt_academic",
        "description": "为GPT/GLM等LLM大语言模型提供实用化交互接口，特别优化论文阅读/润色/写作体验，模块化设计，支持自定义快捷按钮&函数插件，支持Python和C++等项目剖析&自译解功能，PDF/LaTex论文翻译&总结功能，支持并行问询多种LLM模型，支持chatglm3等本地模型。接入通义千问, deepseekcoder, 讯飞星火, 文心一言, llama2, rwkv, claude2, moss等。",
        "category": "model",
        "source": "github",
        "repo": "binary-husky/gpt_academic",
        "platform": "github",
        "tags": ['claude', 'deepseek', 'llama', 'llm', 'gpt'],
        "metadata": {'stars': 69978, 'updated_at': '2026-01-16T14:26:37Z', 'quality_score': 100.0, 'quality_details': {'source': 100.0, 'relevance': 100.0, 'freshness': 100.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://github.com/vllm-project/vllm",
        "name": "vllm",
        "description": "A high-throughput and memory-efficient inference and serving engine for LLMs",
        "category": "inference",
        "source": "github",
        "repo": "vllm-project/vllm",
        "platform": "github",
        "tags": ['vllm', 'llm'],
        "metadata": {'stars': 67672, 'updated_at': '2026-01-16T19:40:07Z', 'quality_score': 100.0, 'quality_details': {'source': 100.0, 'relevance': 100.0, 'freshness': 100.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://github.com/unslothai/unsloth",
        "name": "unsloth",
        "description": "Fine-tuning & Reinforcement Learning for LLMs. 🦥 Train OpenAI gpt-oss, DeepSeek, Qwen, Llama, Gemma, TTS 2x faster with 70% less VRAM.",
        "category": "model",
        "source": "github",
        "repo": "unslothai/unsloth",
        "platform": "github",
        "tags": ['deepseek', 'llama', 'llm', 'openai', 'qwen', 'gpt'],
        "metadata": {'stars': 50783, 'updated_at': '2026-01-16T19:13:04Z', 'quality_score': 100.0, 'quality_details': {'source': 100.0, 'relevance': 100.0, 'freshness': 100.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://openai.com/index/introducing-gpt-5-2/",
        "name": "GPT-5.2",
        "description": "<a href=\"https:&#x2F;&#x2F;platform.openai.com&#x2F;docs&#x2F;guides&#x2F;latest-model\" rel=\"nofollow\">https:&#x2F;&#x2F;platform.openai.com&#x2F;docs&#x2F;guides&#x2F;latest-model</a><p>System card: <a href=\"https:&#x2F;&#x2F;cdn.openai.com&#x2F;pdf&#x2F;3a4153c8-c748-4b71-8e31-aecbde944f8d&#x2F;oai_5_2_system-card.pdf\" rel=\"nofollow\">https:&#x2F;&#x2F;cdn.openai.com&#x2F;pdf&#x2F;3a4153c8-c748-4b71-8e31-aecbde944...</a>",
        "category": "api",
        "source": "hackernews",
        "repo": "",
        "platform": "web",
        "tags": ['openai', 'gpt'],
        "metadata": {'points': 1195, 'created_at': '2025-12-11T18:04:47Z', 'quality_score': 98.0, 'quality_details': {'source': 100.0, 'relevance': 100.0, 'freshness': 90.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://www.anthropic.com/news/claude-opus-4-5",
        "name": "Claude Opus 4.5",
        "description": "<a href=\"https:&#x2F;&#x2F;platform.claude.com&#x2F;docs&#x2F;en&#x2F;about-claude&#x2F;models&#x2F;whats-new-claude-4-5\" rel=\"nofollow\">https:&#x2F;&#x2F;platform.claude.com&#x2F;docs&#x2F;en&#x2F;about-claude&#x2F;models&#x2F;what...</a>",
        "category": "other",
        "source": "hackernews",
        "repo": "",
        "platform": "web",
        "tags": ['claude'],
        "metadata": {'points': 1113, 'created_at': '2025-11-24T18:53:05Z', 'quality_score': 98.0, 'quality_details': {'source': 100.0, 'relevance': 100.0, 'freshness': 90.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://github.com/simstudioai/sim",
        "name": "Show HN: Sim – Apache-2.0 n8n alternative",
        "description": "Hey HN, Waleed here. We&#x27;re building Sim (<a href=\"https:&#x2F;&#x2F;sim.ai&#x2F;\">https:&#x2F;&#x2F;sim.ai&#x2F;</a>), an open-source visual editor to build agentic workflows. Repo here: <a href=\"https:&#x2F;&#x2F;github.com&#x2F;simstudioai&#x2F;sim&#x2F;\" rel=\"nofollow\">https:&#x2F;&#x2F;github.com&#x2F;simstudioai&#x2F;sim&#x2F;</a>. Docs here: <a href=\"https:&#x2F;&#x2F;docs.sim.ai\">https:&#x2F;&#x2F;docs.sim.ai</a>.<p>You can run Sim locally using Docker, with no execution limits or ot",
        "category": "model",
        "source": "hackernews",
        "repo": "simstudioai/sim",
        "platform": "github",
        "tags": ['vllm', 'llama', 'ollama', 'llm', 'openai', 'gemini', 'anthropic'],
        "metadata": {'points': 240, 'created_at': '2025-12-11T17:20:11Z', 'quality_score': 98.0, 'quality_details': {'source': 100.0, 'relevance': 100.0, 'freshness': 90.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://github.com/mlabonne/llm-course",
        "name": "llm-course",
        "description": "Course to get into Large Language Models (LLMs) with roadmaps and Colab notebooks.",
        "category": "other",
        "source": "github",
        "repo": "mlabonne/llm-course",
        "platform": "github",
        "tags": ['llm'],
        "metadata": {'stars': 73198, 'updated_at': '2026-01-16T19:36:14Z', 'quality_score': 97.0, 'quality_details': {'source': 100.0, 'relevance': 90, 'freshness': 100.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://github.com/Hannibal046/Awesome-LLM",
        "name": "Awesome-LLM",
        "description": "Awesome-LLM: a curated list of Large Language Model",
        "category": "other",
        "source": "github",
        "repo": "Hannibal046/Awesome-LLM",
        "platform": "github",
        "tags": ['llm'],
        "metadata": {'stars': 26031, 'updated_at': '2026-01-16T17:05:48Z', 'quality_score': 97.0, 'quality_details': {'source': 100.0, 'relevance': 90, 'freshness': 100.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://github.com/nomic-ai/gpt4all",
        "name": "gpt4all",
        "description": "GPT4All: Run Local LLMs on Any Device. Open-source and available for commercial use.",
        "category": "other",
        "source": "github",
        "repo": "nomic-ai/gpt4all",
        "platform": "github",
        "tags": ['gpt', 'llm'],
        "metadata": {'stars': 77038, 'updated_at': '2026-01-16T14:55:30Z', 'quality_score': 97.0, 'quality_details': {'source': 100.0, 'relevance': 90, 'freshness': 100.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://github.com/rasbt/LLMs-from-scratch",
        "name": "LLMs-from-scratch",
        "description": "Implement a ChatGPT-like LLM in PyTorch from scratch, step by step",
        "category": "other",
        "source": "github",
        "repo": "rasbt/LLMs-from-scratch",
        "platform": "github",
        "tags": ['gpt', 'llm'],
        "metadata": {'stars': 83174, 'updated_at': '2026-01-16T18:45:02Z', 'quality_score': 97.0, 'quality_details': {'source': 100.0, 'relevance': 90, 'freshness': 100.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://github.com/hiyouga/LlamaFactory",
        "name": "LlamaFactory",
        "description": "Unified Efficient Fine-Tuning of 100+ LLMs & VLMs (ACL 2024)",
        "category": "model",
        "source": "github",
        "repo": "hiyouga/LlamaFactory",
        "platform": "github",
        "tags": ['llama', 'llm'],
        "metadata": {'stars': 65889, 'updated_at': '2026-01-16T18:20:12Z', 'quality_score': 97.0, 'quality_details': {'source': 100.0, 'relevance': 90, 'freshness': 100.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://openai.com/gpt-5/",
        "name": "GPT-5",
        "description": "<a href=\"https:&#x2F;&#x2F;www.youtube.com&#x2F;watch?v=0Uu_VJeVVfo\" rel=\"nofollow\">https:&#x2F;&#x2F;www.youtube.com&#x2F;watch?v=0Uu_VJeVVfo</a>",
        "category": "other",
        "source": "hackernews",
        "repo": "",
        "platform": "web",
        "tags": ['gpt'],
        "metadata": {'points': 2063, 'created_at': '2025-08-07T17:00:21Z', 'quality_score': 95.0, 'quality_details': {'source': 100.0, 'relevance': 100.0, 'freshness': 75.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://www.anthropic.com/news/claude-sonnet-4-5",
        "name": "Claude Sonnet 4.5",
        "description": "System card: <a href=\"https:&#x2F;&#x2F;assets.anthropic.com&#x2F;m&#x2F;12f214efcc2f457a&#x2F;original&#x2F;Claude-Sonnet-4-5-System-Card.pdf\" rel=\"nofollow\">https:&#x2F;&#x2F;assets.anthropic.com&#x2F;m&#x2F;12f214efcc2f457a&#x2F;original&#x2F;Cla...</a>",
        "category": "api",
        "source": "hackernews",
        "repo": "",
        "platform": "web",
        "tags": ['claude', 'anthropic'],
        "metadata": {'points': 1585, 'created_at': '2025-09-29T16:52:59Z', 'quality_score': 95.0, 'quality_details': {'source': 100.0, 'relevance': 100.0, 'freshness': 75.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://openai.com/open-models/",
        "name": "Open models by OpenAI",
        "description": "<a href=\"https:&#x2F;&#x2F;openai.com&#x2F;index&#x2F;introducing-gpt-oss&#x2F;\" rel=\"nofollow\">https:&#x2F;&#x2F;openai.com&#x2F;index&#x2F;introducing-gpt-oss&#x2F;</a>",
        "category": "api",
        "source": "hackernews",
        "repo": "",
        "platform": "web",
        "tags": ['openai', 'gpt'],
        "metadata": {'points': 2124, 'created_at': '2025-08-05T17:02:02Z', 'quality_score': 95.0, 'quality_details': {'source': 100.0, 'relevance': 100.0, 'freshness': 75.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://github.com/JerryZLiu/Dayflow",
        "name": "Show HN: Dayflow – A git log for your day",
        "description": "Hi HN! I&#x27;ve been building Dayflow, a macOS app that automatically tracks what you&#x27;re actually working on (not just which apps you have open).<p>Here&#x27;s what it does:<p>- It creates a semantic timeline of your day;<p>- It does it by understanding the content on your screen (with local or cloud VLMs);<p>- This allows you to see exactly where your time went without any manual logging.<p>Traditional time trackers tell you &quot;3 hours in Chrome&quot; which is not very helpful. Dayflow",
        "category": "model",
        "source": "hackernews",
        "repo": "JerryZLiu/Dayflow",
        "platform": "github",
        "tags": ['llama', 'ollama', 'llm', 'gemini', 'qwen'],
        "metadata": {'points': 480, 'created_at': '2025-09-24T14:53:57Z', 'quality_score': 95.0, 'quality_details': {'source': 100.0, 'relevance': 100.0, 'freshness': 75.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://github.com/Significant-Gravitas/AutoGPT",
        "name": "AutoGPT",
        "description": "AutoGPT is the vision of accessible AI for everyone, to use and to build on. Our mission is to provide the tools, so that you can focus on what matters.",
        "category": "other",
        "source": "github",
        "repo": "Significant-Gravitas/AutoGPT",
        "platform": "github",
        "tags": ['gpt'],
        "metadata": {'stars': 181150, 'updated_at': '2026-01-16T19:05:38Z', 'quality_score': 92.5, 'quality_details': {'source': 100.0, 'relevance': 75, 'freshness': 100.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://github.com/f/awesome-chatgpt-prompts",
        "name": "awesome-chatgpt-prompts",
        "description": "Share, discover, and collect prompts from the community. Free and open source — self-host for your organization with complete privacy.",
        "category": "other",
        "source": "github",
        "repo": "f/awesome-chatgpt-prompts",
        "platform": "github",
        "tags": ['gpt'],
        "metadata": {'stars': 142459, 'updated_at': '2026-01-16T19:43:18Z', 'quality_score': 92.5, 'quality_details': {'source': 100.0, 'relevance': 75, 'freshness': 100.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://github.com/Mintplex-Labs/anything-llm",
        "name": "anything-llm",
        "description": "The all-in-one Desktop & Docker AI application with built-in RAG, AI agents, No-code agent builder, MCP compatibility,  and more.",
        "category": "other",
        "source": "github",
        "repo": "Mintplex-Labs/anything-llm",
        "platform": "github",
        "tags": ['llm'],
        "metadata": {'stars': 53408, 'updated_at': '2026-01-16T18:44:32Z', 'quality_score': 92.5, 'quality_details': {'source': 100.0, 'relevance': 75, 'freshness': 100.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://github.com/cactus-compute/cactus",
        "name": "Launch HN: Cactus (YC S25) – AI inference on smartphones",
        "description": "Hey HN, Henry &amp; Roman here, we are building Cactus (<a href=\"https:&#x2F;&#x2F;cactuscompute.com&#x2F;\">https:&#x2F;&#x2F;cactuscompute.com&#x2F;</a>), an AI inference engine specifically designed for phones.<p>We&#x27;re seeing a major push towards on-device AI, and for good reason: on-device AI decreases latency from &gt;1sec to &lt;100ms, guarantees privacy by default, works offline, and doesn&#x27;t rack up a massive API bill at scale.<p>Also, tools and agentic designs make small models ",
        "category": "model",
        "source": "hackernews",
        "repo": "cactus-compute/cactus",
        "platform": "github",
        "tags": ['vllm', 'llama', 'ollama', 'llm', 'huggingface', 'qwen'],
        "metadata": {'points': 123, 'created_at': '2025-09-18T15:40:29Z', 'quality_score': 92.0, 'quality_details': {'source': 100.0, 'relevance': 100.0, 'freshness': 75.0, 'activity': 85.0}},
        "is_active": True,
    },
    {
        "url": "https://github.com/katanemo/archgw/",
        "name": "Show HN: ArchGW – An intelligent edge and service proxy for agents",
        "description": "Hey HN!<p>This is Adil, Salman and Jose and and we’re behind archgw [1]. An intelligent proxy server designed as an edge and AI gateway for agents - one that natively know how to handle prompts, not just network traffic. We’ve made several sweeping changes so sharing the project again.<p>A bit of background on why we’ve built this project. Building AI agent demos is easy, but to create something production-ready there is a lot of repeat low-level plumbing work that everyone is doing. You’re appl",
        "category": "other",
        "source": "hackernews",
        "repo": "katanemo/archgw",
        "platform": "github",
        "tags": ['huggingface', 'llm'],
        "metadata": {'points': 118, 'created_at': '2025-07-12T23:55:39Z', 'quality_score': 89.0, 'quality_details': {'source': 100.0, 'relevance': 100.0, 'freshness': 60.0, 'activity': 85.0}},
        "is_active": True,
    },
    {
        "url": "https://github.com/microsoft/aici",
        "name": "Show HN: Prompts as WASM Programs",
        "description": "AICI is a proposed common interface between LLM inference engines (llama.cpp, vLLM, HF Transformers, etc.) and &quot;controllers&quot; - programs that can constrain the LLM output according to regexp, grammar, or custom logic, as well as control the generation process (forking, backtracking, etc.).<p>AICI is based on Wasm, and is designed to be fast (runs on CPU while GPU is busy), secure (can run in multi-tenant cloud deployments), and flexible (allow libraries like Guidance, LMQL, Outlines, et",
        "category": "model",
        "source": "hackernews",
        "repo": "microsoft/aici",
        "platform": "github",
        "tags": ['transformers', 'vllm', 'llama', 'llm'],
        "metadata": {'points': 209, 'created_at': '2024-03-11T17:00:49Z', 'quality_score': 88.0, 'quality_details': {'source': 100.0, 'relevance': 100.0, 'freshness': 40.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://github.com/abi/secret-llama",
        "name": "Show HN: I built a free in-browser Llama 3 chatbot powered by WebGPU",
        "description": "I spent the last few days building out a nicer ChatGPT-like interface to use Mistral 7B and Llama 3 fully within a browser (no deps and installs).<p>I’ve used the WebLLM project by MLC AI for a while to interact with LLMs in the browser when handling sensitive data but I found their UI quite lacking for serious use so I built a much better interface around WebLLM.<p>I’ve been using it as a therapist and coach. And it’s wonderful knowing that my personal information never leaves my local computer",
        "category": "model",
        "source": "hackernews",
        "repo": "abi/secret-llama",
        "platform": "github",
        "tags": ['mistral', 'llama', 'llm', 'chatbot', 'gpt'],
        "metadata": {'points': 547, 'created_at': '2024-05-03T21:26:46Z', 'quality_score': 88.0, 'quality_details': {'source': 100.0, 'relevance': 100.0, 'freshness': 40.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://github.com/x1xhlol/system-prompts-and-models-of-ai-tools",
        "name": "system-prompts-and-models-of-ai-tools",
        "description": "FULL Augment Code, Claude Code, Cluely, CodeBuddy, Comet, Cursor, Devin AI, Junie, Kiro, Leap.new, Lovable, Manus, NotionAI, Orchids.app, Perplexity, Poke, Qoder, Replit, Same.dev, Trae, Traycer AI, VSCode Agent, Warp.dev, Windsurf, Xcode, Z.ai Code, Dia & v0. (And other Open Sourced) System Prompts, Internal Tools & AI Models",
        "category": "other",
        "source": "github",
        "repo": "x1xhlol/system-prompts-and-models-of-ai-tools",
        "platform": "github",
        "tags": ['claude'],
        "metadata": {'stars': 108678, 'updated_at': '2026-01-16T19:41:25Z', 'quality_score': 86.5, 'quality_details': {'source': 100.0, 'relevance': 55, 'freshness': 100.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://github.com/PaddlePaddle/PaddleOCR",
        "name": "PaddleOCR",
        "description": "Turn any PDF or image document into structured data for your AI. A powerful, lightweight OCR toolkit that bridges the gap between images/PDFs and LLMs. Supports 100+ languages.",
        "category": "other",
        "source": "github",
        "repo": "PaddlePaddle/PaddleOCR",
        "platform": "github",
        "tags": ['llm'],
        "metadata": {'stars': 68167, 'updated_at': '2026-01-16T18:11:00Z', 'quality_score': 86.5, 'quality_details': {'source': 100.0, 'relevance': 55, 'freshness': 100.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://github.com/opendatalab/MinerU",
        "name": "MinerU",
        "description": "Transforms complex documents like PDFs into LLM-ready markdown/JSON for your Agentic workflows.",
        "category": "other",
        "source": "github",
        "repo": "opendatalab/MinerU",
        "platform": "github",
        "tags": ['llm'],
        "metadata": {'stars': 52238, 'updated_at': '2026-01-16T19:39:52Z', 'quality_score': 86.5, 'quality_details': {'source': 100.0, 'relevance': 55, 'freshness': 100.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://evan.widloski.com/software/sms_llm/",
        "name": "Show HN: Trolling SMS spammers with Ollama",
        "description": "I&#x27;ve been working on a side project to generate responses to spam with various funny LLM personas, such as a millenial gym bro and a 19th century British gentleman. By request, I&#x27;ve made a write-up on my website which has some humorous screenshots and made the code available on Github for others to try out [0].<p>A brief outline of the system:<p>- Android app listens for incoming SMS events and forwards them over MQTT to a server running Ollama which generates responses - Conversations",
        "category": "model",
        "source": "hackernews",
        "repo": "",
        "platform": "web",
        "tags": ['llama', 'ollama', 'llm'],
        "metadata": {'points': 318, 'created_at': '2025-01-22T19:23:48Z', 'quality_score': 83.0, 'quality_details': {'source': 70.0, 'relevance': 100.0, 'freshness': 60.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://asciinema.org/a/piP22yYwcaohu5cA2gyuv1W61",
        "name": "Show HN: Speeding up LLM inference 2x times (possibly)",
        "description": "Here&#x27;s a project I&#x27;ve been working on for the last few months.<p>It&#x27;s a new (I think) algorithm, that allows to adjust smoothly - and in real time - how many calculations you&#x27;d like to do during inference of an LLM model.<p>It seems that it&#x27;s possible to do just 20-25% of weight multiplications instead of all of them, and still get good inference results.<p>I implemented it to run on M1&#x2F;M2&#x2F;M3 GPU. The mmul approximation itself can be pushed to run 2x fast befor",
        "category": "model",
        "source": "hackernews",
        "repo": "",
        "platform": "web",
        "tags": ['mistral', 'llama', 'llm'],
        "metadata": {'points': 419, 'created_at': '2024-04-17T17:26:09Z', 'quality_score': 79.0, 'quality_details': {'source': 70.0, 'relevance': 100.0, 'freshness': 40.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://getomni.ai/ocr-benchmark",
        "name": "Show HN: Benchmarking VLMs vs. Traditional OCR",
        "description": "Vision models have been gaining popularity as a replacement for traditional OCR. Especially with Gemini 2.0 becoming cost competitive with the cloud platforms.<p>We&#x27;ve been continuously evaluating different models since we released the Zerox package last year (<a href=\"https:&#x2F;&#x2F;github.com&#x2F;getomni-ai&#x2F;zerox\">https:&#x2F;&#x2F;github.com&#x2F;getomni-ai&#x2F;zerox</a>). And we wanted to put some numbers behind it. So we’re open sourcing our internal OCR benchmark + evaluatio",
        "category": "other",
        "source": "hackernews",
        "repo": "",
        "platform": "web",
        "tags": ['huggingface', 'gemini', 'llm'],
        "metadata": {'points': 146, 'created_at': '2025-02-20T18:49:29Z', 'quality_score': 78.5, 'quality_details': {'source': 65.0, 'relevance': 100.0, 'freshness': 60.0, 'activity': 85.0}},
        "is_active": True,
    },
    {
        "url": "https://www.phind.com/phindmodelhn",
        "name": "Phind Model beats GPT-4 at coding, with GPT-3.5 speed and 16k context",
        "description": "Hi HN,<p>We’re excited to announce that Phind now defaults to our own model that matches and exceeds GPT-4’s coding abilities while running 5x faster. You can now get high quality answers for technical questions in 10 seconds instead of 50.<p>The current 7th-generation Phind Model is built on top of our open-source CodeLlama-34B fine-tunes that were the first models to beat GPT-4’s score on HumanEval and are still the best open source coding models overall by a wide margin: <a href=\"https:&#x2F;",
        "category": "model",
        "source": "hackernews",
        "repo": "",
        "platform": "web",
        "tags": ['huggingface', 'llama', 'gpt', 'llm'],
        "metadata": {'points': 891, 'created_at': '2023-10-31T17:40:47Z', 'quality_score': 75.0, 'quality_details': {'source': 70.0, 'relevance': 100.0, 'freshness': 20.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://www.phind.com/blog/code-llama-beats-gpt4",
        "name": "Beating GPT-4 on HumanEval with a fine-tuned CodeLlama-34B",
        "description": "Hi HN,<p>We have fine-tuned CodeLlama-34B and CodeLlama-34B-Python on an internal Phind dataset that achieved 67.6% and 69.5% pass@1 on HumanEval, respectively. GPT-4 achieved 67%. To ensure result validity, we applied OpenAI&#x27;s decontamination methodology to our dataset.<p>The CodeLlama models released yesterday demonstrate impressive performance on HumanEval.<p>- CodeLlama-34B achieved 48.8% pass@1 on HumanEval<p>- CodeLlama-34B-Python achieved 53.7% pass@1 on HumanEval<p>We have fine-tune",
        "category": "model",
        "source": "hackernews",
        "repo": "",
        "platform": "web",
        "tags": ['huggingface', 'openai', 'llama', 'gpt'],
        "metadata": {'points': 813, 'created_at': '2023-08-25T22:08:23Z', 'quality_score': 75.0, 'quality_details': {'source': 70.0, 'relevance': 100.0, 'freshness': 20.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://chatllama.baseten.co/",
        "name": "Show HN: ChatLLaMA – A ChatGPT style chatbot for Facebook's LLaMA",
        "description": "ChatLLaMA is an experimental chatbot interface for interacting with variants of Facebook&#x27;s LLaMA. Currently, we support the 7 billion parameter variant that was fine-tuned on the Alpaca dataset. This early versions isn&#x27;t as conversational as we&#x27;d like, but over the next week or so, we&#x27;re planning on adding support for the 30 billion parameter variant, another variant fine-tuned on LAION&#x27;s OpenAssistant dataset and more as we explore what this model is capable of.<p>If yo",
        "category": "model",
        "source": "hackernews",
        "repo": "",
        "platform": "web",
        "tags": ['llama', 'chatbot', 'gpt'],
        "metadata": {'points': 402, 'created_at': '2023-03-22T09:07:28Z', 'quality_score': 75.0, 'quality_details': {'source': 70.0, 'relevance': 100.0, 'freshness': 20.0, 'activity': 100.0}},
        "is_active": True,
    },
    {
        "url": "https://glhf.chat/landing/home",
        "name": "Show HN: We made glhf.chat – run almost any open-source LLM, including 405B",
        "description": "Try it out! <a href=\"https:&#x2F;&#x2F;glhf.chat&#x2F;\" rel=\"nofollow\">https:&#x2F;&#x2F;glhf.chat&#x2F;</a><p>Hey HN!<p>We’ve been working for the past few months on a website to let you easily run (almost) any open-source LLM on autoscaling GPU clusters. It’s free for now while we figure out how to price it, but we expect to be cheaper than most GPU offerings since we can run the models multi-tenant.<p>Unlike Together AI, Fireworks, etc, we’ll run any model that the open-source vLLM project su",
        "category": "model",
        "source": "hackernews",
        "repo": "",
        "platform": "web",
        "tags": ['deepseek', 'vllm', 'llama', 'llm'],
        "metadata": {'points': 161, 'created_at': '2024-07-24T01:52:09Z', 'quality_score': 74.5, 'quality_details': {'source': 65.0, 'relevance': 100.0, 'freshness': 40.0, 'activity': 85.0}},
        "is_active": True,
    },
    {
        "url": "https://finetunedb.com",
        "name": "Show HN: FinetuneDB – AI fine-tuning platform to create custom LLMs",
        "description": "Hey HN! We’re building FinetuneDB (<a href=\"https:&#x2F;&#x2F;finetunedb.com&#x2F;\" rel=\"nofollow\">https:&#x2F;&#x2F;finetunedb.com&#x2F;</a>), an LLM fine-tuning platform. It enables teams to easily create and manage high-quality datasets, and streamlines the entire workflow from fine-tuning to serving and evaluating models with domain experts. You can check out our docs here: (<a href=\"https:&#x2F;&#x2F;docs.finetunedb.com&#x2F;\" rel=\"nofollow\">https:&#x2F;&#x2F;docs.finetunedb.com&#x2F;</a>)<",
        "category": "model",
        "source": "hackernews",
        "repo": "",
        "platform": "web",
        "tags": ['mistral', 'openai', 'llama', 'llm'],
        "metadata": {'points': 152, 'created_at': '2024-10-09T15:44:53Z', 'quality_score': 74.5, 'quality_details': {'source': 65.0, 'relevance': 100.0, 'freshness': 40.0, 'activity': 85.0}},
        "is_active": True,
    },
    {
        "url": "https://www.phind.com",
        "name": "Show HN: GPT-4-powered web searches for developers",
        "description": "Hi HN,<p>Today we’re launching GPT-4 answers on Phind.com, a developer-focused search engine that uses generative AI to browse the web and answer technical questions, complete with code examples and detailed explanations. Unlike vanilla GPT-4, Phind feeds in relevant websites and technical documentation, reducing the model’s hallucination and keeping it up-to-date. To use it, simply enable the “Expert” toggle before doing a search.<p>GPT-4 is making a night-and-day difference in terms of answer ",
        "category": "model",
        "source": "hackernews",
        "repo": "",
        "platform": "web",
        "tags": ['llama', 'gpt'],
        "metadata": {'points': 1401, 'created_at': '2023-04-12T17:44:08Z', 'quality_score': 72.0, 'quality_details': {'source': 70.0, 'relevance': 90, 'freshness': 20.0, 'activity': 100.0}},
        "is_active": True,
    },
]
